In [ ]:
import sqlite3 as sql
import pandas as pd
import glob
from pathlib import Path

In [ ]:
Path("barrels.db").touch()

In [ ]:
db = "barrels.db"
with sql.connect(db, timeout = 1000) as conn:
    cur = conn.cursor()

In [ ]:
for file in glob.glob("data/*.csv"):
    df = pd.read_csv(file)
    print("Creating Table", file[5:-4].replace("-",""))
    df.to_sql(file[5:-4].replace("-",""), conn, if_exists="replace", index=False)

Creating Table gameinfo
Creating Table lineups

In [ ]:
ball_events_names = []
for file in glob.glob("data/ball-events/*/*/*/*/*.csv"):
    print(file)
    df = pd.read_csv(file)
    print("Creating Table", f'events_{file[28:-16].replace(".5","_5")}')
    ball_events_names.append(f'events_{file[28:-16].replace(".5","_5")}')
    df.to_sql(f'events_{file[28:-16].replace(".5","_5")}', conn, if_exists="replace", index=False)

data/ball-events\ANI\ADQ\y1\d143\ball_events.csv
Creating Table events_d143
data/ball-events\ANI\ADQ\y1\d144\ball_events.csv
Creating Table events_d144
data/ball-events\ANI\ADQ\y1\d145\ball_events.csv
Creating Table events_d145
data/ball-events\ANI\ADQ\y1\d146\ball_events.csv
Creating Table events_d146
data/ball-events\ANI\EMB\y1\d167\ball_events.csv
Creating Table events_d167
data/ball-events\ANI\EMB\y1\d168\ball_events.csv
Creating Table events_d168
data/ball-events\ANI\EMB\y1\d169\ball_events.csv
Creating Table events_d169
data/ball-events\ANI\FET\y1\d178\ball_events.csv
Creating Table events_d178
data/ball-events\ANI\FET\y1\d179\ball_events.csv
Creating Table events_d179
data/ball-events\ANI\FET\y1\d180\ball_events.csv
Creating Table events_d180
data/ball-events\ANI\FXP\y1\d194\ball_events.csv
Creating Table events_d194
data/ball-events\ANI\FXP\y1\d195\ball_events.csv
Creating Table events_d195
data/ball-events\ANI\FXP\y1\d196\ball_events.csv
Creating Table events_d196
data/ball-events\ANI\FXP\y1\d197\ball_events.csv
Creating Table events_d197
data/ball-events\ANI\IGL\y1\d171\ball_events.csv
Creating Table events_d171
data/ball-events\ANI\IGL\y1\d172\ball_events.csv
Creating Table events_d172
data/ball-events\ANI\IGL\y1\d173\ball_events.csv
Creating Table events_d173
data/ball-events\ANI\JPB\y1\d112\ball_events.csv
Creating Table events_d112
data/ball-events\ANI\JPB\y1\d113\ball_events.csv
Creating Table events_d113
data/ball-events\ANI\JPB\y1\d114\ball_events.csv
Creating Table events_d114
data/ball-events\ANI\JPB\y1\d115\ball_events.csv
Creating Table events_d115
data/ball-events\ANI\MEX\y1\d125\ball_events.csv
Creating Table events_d125
data/ball-events\ANI\MEX\y1\d126\ball_events.csv
Creating Table events_d126
data/ball-events\ANI\MEX\y1\d127\ball_events.csv
Creating Table events_d127
data/ball-events\ANI\MEX\y1\d128\ball_events.csv
Creating Table events_d128
data/ball-events\ANI\MSE\y1\d122\ball_events.csv
Creating Table events_d122
data/ball-events\ANI\MSE\y1\d123\ball_events.csv
Creating Table events_d123
data/ball-events\ANI\MSE\y1\d124\ball_events.csv
Creating Table events_d124
data/ball-events\ANI\NLG\y1\d067.5\ball_events.csv
Creating Table events_d067_5
data/ball-events\ANI\OER\y1\d105\ball_events.csv
Creating Table events_d105
data/ball-events\ANI\OER\y1\d105.5\ball_events.csv
Creating Table events_d105_5
data/ball-events\ANI\OER\y1\d106\ball_events.csv
Creating Table events_d106
data/ball-events\ANI\OER\y1\d106.5\ball_events.csv
Creating Table events_d106_5
data/ball-events\ANI\OER\y1\d107\ball_events.csv
Creating Table events_d107
data/ball-events\ANI\QBR\y1\d138\ball_events.csv
Creating Table events_d138
data/ball-events\ANI\QBR\y1\d139\ball_events.csv
Creating Table events_d139
data/ball-events\ANI\QBR\y1\d140\ball_events.csv
Creating Table events_d140
data/ball-events\ANI\QBR\y1\d141\ball_events.csv
Creating Table events_d141
data/ball-events\ANI\QHX\y1\d209\ball_events.csv
Creating Table events_d209
data/ball-events\ANI\QHX\y1\d210\ball_events.csv
Creating Table events_d210
data/ball-events\ANI\QHX\y1\d211\ball_events.csv
Creating Table events_d211
data/ball-events\ANI\QHX\y1\d212\ball_events.csv
Creating Table events_d212
data/ball-events\ANI\SZJ\y1\d163\ball_events.csv
Creating Table events_d163
data/ball-events\ANI\SZJ\y1\d164\ball_events.csv
Creating Table events_d164
data/ball-events\ANI\SZJ\y1\d164.5\ball_events.csv
Creating Table events_d164_5
data/ball-events\ANI\SZJ\y1\d165\ball_events.csv
Creating Table events_d165
data/ball-events\ANI\SZJ\y1\d166\ball_events.csv
Creating Table events_d166
data/ball-events\ANI\WIF\y1\d181\ball_events.csv
Creating Table events_d181
data/ball-events\ANI\WIF\y1\d182\ball_events.csv
Creating Table events_d182
data/ball-events\ANI\WIF\y1\d183\ball_events.csv
Creating Table events_d183
data/ball-events\ANI\WIF\y1\d184\ball_events.csv
Creating Table events_d184
data/ball-events\ARN\AIP\y1\d074\ball_events.csv
Creating Table events_d074
data/ball-events\ARN\AIP\y1\d074.5\ball_events.csv
Creating Table events_d074_5
data/ball-events\ARN\ALC\y1\d144\ball_events.csv
Creating Table events_d144
data/ball-events\ARN\ALC\y1\d145\ball_events.csv
Creating Table events_d145
data/ball-events\ARN\AVV\y1\d177\ball_events.csv
Creating Table events_d177
data/ball-events\ARN\AVV\y1\d178\ball_events.csv
Creating Table events_d178
data/ball-events\ARN\BTL\y1\d167\ball_events.csv
Creating Table events_d167
data/ball-events\ARN\BTL\y1\d168\ball_events.csv
Creating Table events_d168
data/ball-events\ARN\BTL\y1\d169\ball_events.csv
Creating Table events_d169
data/ball-events\ARN\EXB\y1\d136\ball_events.csv
Creating Table events_d136
data/ball-events\ARN\EXB\y1\d137\ball_events.csv
Creating Table events_d137
data/ball-events\ARN\EXB\y1\d138\ball_events.csv
Creating Table events_d138
data/ball-events\ARN\FSD\y1\d104.5\ball_events.csv
Creating Table events_d104_5
data/ball-events\ARN\HNO\y1\d213\ball_events.csv
Creating Table events_d213
data/ball-events\ARN\KTT\y1\d116\ball_events.csv
Creating Table events_d116
data/ball-events\ARN\KTT\y1\d116.5\ball_events.csv
Creating Table events_d116_5
data/ball-events\ARN\LRQ\y1\d181\ball_events.csv
Creating Table events_d181
data/ball-events\ARN\LRQ\y1\d182\ball_events.csv
Creating Table events_d182
data/ball-events\ARN\LRQ\y1\d183\ball_events.csv
Creating Table events_d183
data/ball-events\ARN\MKS\y1\d118\ball_events.csv
Creating Table events_d118
data/ball-events\ARN\MKS\y1\d119\ball_events.csv
Creating Table events_d119
data/ball-events\ARN\MKS\y1\d120\ball_events.csv
Creating Table events_d120
data/ball-events\ARN\NWM\y1\d125\ball_events.csv
Creating Table events_d125
data/ball-events\ARN\NWM\y1\d126\ball_events.csv
Creating Table events_d126
data/ball-events\ARN\NWM\y1\d127\ball_events.csv
Creating Table events_d127
data/ball-events\ARN\NWM\y1\d127.5\ball_events.csv
Creating Table events_d127_5
data/ball-events\ARN\NXS\y1\d083\ball_events.csv
Creating Table events_d083
data/ball-events\ARN\NXS\y1\d084\ball_events.csv
Creating Table events_d084
data/ball-events\ARN\NYN\y1\d097\ball_events.csv
Creating Table events_d097
data/ball-events\ARN\NYN\y1\d098\ball_events.csv
Creating Table events_d098
data/ball-events\ARN\PHD\y1\d188\ball_events.csv
Creating Table events_d188
data/ball-events\ARN\PHD\y1\d189\ball_events.csv
Creating Table events_d189
data/ball-events\ARN\PHD\y1\d190\ball_events.csv
Creating Table events_d190
data/ball-events\ARN\PWH\y1\d209\ball_events.csv
Creating Table events_d209
data/ball-events\ARN\PWH\y1\d210\ball_events.csv
Creating Table events_d210
data/ball-events\ARN\PWH\y1\d211\ball_events.csv
Creating Table events_d211
data/ball-events\ARN\PWH\y1\d212\ball_events.csv
Creating Table events_d212
data/ball-events\ARN\RME\y1\d152\ball_events.csv
Creating Table events_d152
data/ball-events\ARN\RME\y1\d153\ball_events.csv
Creating Table events_d153
data/ball-events\ARN\RME\y1\d153.5\ball_events.csv
Creating Table events_d153_5
data/ball-events\ARN\SQF\y1\d068\ball_events.csv
Creating Table events_d068
data/ball-events\ARN\SQF\y1\d069\ball_events.csv
Creating Table events_d069
data/ball-events\ARN\SQF\y1\d070\ball_events.csv
Creating Table events_d070
data/ball-events\ARN\SQF\y1\d071\ball_events.csv
Creating Table events_d071
data/ball-events\ARN\TDW\y1\d185\ball_events.csv
Creating Table events_d185
data/ball-events\ARN\TDW\y1\d186\ball_events.csv
Creating Table events_d186
data/ball-events\ARN\TDW\y1\d187\ball_events.csv
Creating Table events_d187
data/ball-events\ARN\TES\y1\d198\ball_events.csv
Creating Table events_d198
data/ball-events\ARN\TES\y1\d199\ball_events.csv
Creating Table events_d199
data/ball-events\ARN\TES\y1\d200\ball_events.csv
Creating Table events_d200
data/ball-events\ARN\TES\y1\d201\ball_events.csv
Creating Table events_d201
data/ball-events\ARN\THF\y1\d108\ball_events.csv
Creating Table events_d108
data/ball-events\ARN\THF\y1\d109\ball_events.csv
Creating Table events_d109
data/ball-events\ARN\THF\y1\d110\ball_events.csv
Creating Table events_d110
data/ball-events\ARN\URD\y1\d072\ball_events.csv
Creating Table events_d072
data/ball-events\ARN\VAS\y1\d139\ball_events.csv
Creating Table events_d139
data/ball-events\ARN\VAS\y1\d140\ball_events.csv
Creating Table events_d140
data/ball-events\ARN\VAS\y1\d141\ball_events.csv
Creating Table events_d141
data/ball-events\ARN\VAS\y1\d217\ball_events.csv
Creating Table events_d217
data/ball-events\ARN\WLI\y1\d094\ball_events.csv
Creating Table events_d094
data/ball-events\ARN\WLI\y1\d095\ball_events.csv
Creating Table events_d095
data/ball-events\ARN\WLI\y1\d096\ball_events.csv
Creating Table events_d096
data/ball-events\ARN\XOZ\y1\d155\ball_events.csv
Creating Table events_d155
data/ball-events\ARN\XOZ\y1\d155.5\ball_events.csv
Creating Table events_d155_5
data/ball-events\ARN\ZGC\y1\d086\ball_events.csv
Creating Table events_d086
data/ball-events\ARN\ZGC\y1\d087\ball_events.csv
Creating Table events_d087
data/ball-events\ARN\ZGC\y1\d088\ball_events.csv
Creating Table events_d088
data/ball-events\ARN\ZGC\y1\d089\ball_events.csv
Creating Table events_d089
data/ball-events\PHD\ARN\y1\d195\ball_events.csv
Creating Table events_d195
data/ball-events\PHD\ARN\y1\d196\ball_events.csv
Creating Table events_d196
data/ball-events\PHD\ARN\y1\d197\ball_events.csv
Creating Table events_d197
data/ball-events\PHD\ATL\y1\d205\ball_events.csv
Creating Table events_d205
data/ball-events\PHD\ATL\y1\d206\ball_events.csv
Creating Table events_d206
data/ball-events\PHD\ATL\y1\d207\ball_events.csv
Creating Table events_d207
data/ball-events\PHD\ATL\y1\d208\ball_events.csv
Creating Table events_d208
data/ball-events\PHD\CYU\y1\d097\ball_events.csv
Creating Table events_d097
data/ball-events\PHD\CYU\y1\d098\ball_events.csv
Creating Table events_d098
data/ball-events\PHD\CYU\y1\d099\ball_events.csv
Creating Table events_d099
data/ball-events\PHD\FNQ\y1\d163\ball_events.csv
Creating Table events_d163
data/ball-events\PHD\FNQ\y1\d164\ball_events.csv
Creating Table events_d164
data/ball-events\PHD\FNQ\y1\d165\ball_events.csv
Creating Table events_d165
data/ball-events\PHD\FNQ\y1\d166\ball_events.csv
Creating Table events_d166
data/ball-events\PHD\GNX\y1\d139\ball_events.csv
Creating Table events_d139
data/ball-events\PHD\GNX\y1\d140\ball_events.csv
Creating Table events_d140
data/ball-events\PHD\GNX\y1\d141\ball_events.csv
Creating Table events_d141
data/ball-events\PHD\HYG\y1\d136\ball_events.csv
Creating Table events_d136
data/ball-events\PHD\HYG\y1\d137\ball_events.csv
Creating Table events_d137
data/ball-events\PHD\HYG\y1\d138\ball_events.csv
Creating Table events_d138
data/ball-events\PHD\JJP\y1\d080\ball_events.csv
Creating Table events_d080
data/ball-events\PHD\JJP\y1\d081\ball_events.csv
Creating Table events_d081
data/ball-events\PHD\JJP\y1\d082\ball_events.csv
Creating Table events_d082
data/ball-events\PHD\MPC\y1\d167\ball_events.csv
Creating Table events_d167
data/ball-events\PHD\MPC\y1\d168\ball_events.csv
Creating Table events_d168
data/ball-events\PHD\MPC\y1\d169\ball_events.csv
Creating Table events_d169
data/ball-events\PHD\NFP\y1\d094\ball_events.csv
Creating Table events_d094
data/ball-events\PHD\NFP\y1\d095\ball_events.csv
Creating Table events_d095
data/ball-events\PHD\NFP\y1\d096\ball_events.csv
Creating Table events_d096
data/ball-events\PHD\RYU\y1\d083\ball_events.csv
Creating Table events_d083
data/ball-events\PHD\RYU\y1\d084\ball_events.csv
Creating Table events_d084
data/ball-events\PHD\RYU\y1\d085\ball_events.csv
Creating Table events_d085
data/ball-events\PHD\SPL\y1\d108\ball_events.csv
Creating Table events_d108
data/ball-events\PHD\SPL\y1\d109\ball_events.csv
Creating Table events_d109
data/ball-events\PHD\SPL\y1\d110\ball_events.csv
Creating Table events_d110
data/ball-events\PHD\TQS\y1\d181\ball_events.csv
Creating Table events_d181
data/ball-events\PHD\TQS\y1\d182\ball_events.csv
Creating Table events_d182
data/ball-events\PHD\VAS\y1\d065\ball_events.csv
Creating Table events_d065
data/ball-events\PHD\VAS\y1\d066\ball_events.csv
Creating Table events_d066
data/ball-events\PHD\VAS\y1\d124\ball_events.csv
Creating Table events_d124
data/ball-events\PHD\VAS\y1\d125\ball_events.csv
Creating Table events_d125
data/ball-events\PHD\VAS\y1\d127\ball_events.csv
Creating Table events_d127
data/ball-events\PHD\VAS\y1\d152\ball_events.csv
Creating Table events_d152
data/ball-events\PHD\VAS\y1\d153\ball_events.csv
Creating Table events_d153
data/ball-events\PHD\VAS\y1\d153.5\ball_events.csv
Creating Table events_d153_5
data/ball-events\PHD\VAS\y1\d154\ball_events.csv
Creating Table events_d154
data/ball-events\PHD\VAS\y1\d155\ball_events.csv
Creating Table events_d155
data/ball-events\PHD\VAS\y1\d177\ball_events.csv
Creating Table events_d177
data/ball-events\PHD\VAS\y1\d178\ball_events.csv
Creating Table events_d178
data/ball-events\PHD\VHA\y1\d146\ball_events.csv
Creating Table events_d146
data/ball-events\PHD\VHA\y1\d147\ball_events.csv
Creating Table events_d147
data/ball-events\PHD\VHA\y1\d148\ball_events.csv
Creating Table events_d148
data/ball-events\PHD\VKA\y1\d061\ball_events.csv
Creating Table events_d061
data/ball-events\PHD\VKA\y1\d062\ball_events.csv
Creating Table events_d062
data/ball-events\PHD\VKA\y1\d063\ball_events.csv
Creating Table events_d063
data/ball-events\PHD\VKA\y1\d064\ball_events.csv
Creating Table events_d064
data/ball-events\PHD\XGM\y1\d111\ball_events.csv
Creating Table events_d111
data/ball-events\PHD\XGM\y1\d112\ball_events.csv
Creating Table events_d112
data/ball-events\PHD\XGM\y1\d113\ball_events.csv
Creating Table events_d113
data/ball-events\PHD\XGM\y1\d114\ball_events.csv
Creating Table events_d114
data/ball-events\PHD\XPO\y1\d072\ball_events.csv
Creating Table events_d072
data/ball-events\PHD\XPO\y1\d073\ball_events.csv
Creating Table events_d073
data/ball-events\PHD\XPO\y1\d074\ball_events.csv
Creating Table events_d074
data/ball-events\PHD\XPO\y1\d075\ball_events.csv
Creating Table events_d075
data/ball-events\PHD\YXL\y1\d179\ball_events.csv
Creating Table events_d179
data/ball-events\PHD\YXL\y1\d180\ball_events.csv
Creating Table events_d180
data/ball-events\VAS\ARN\y1\d132\ball_events.csv
Creating Table events_d132
data/ball-events\VAS\ARN\y1\d133\ball_events.csv
Creating Table events_d133
data/ball-events\VAS\ARN\y1\d134\ball_events.csv
Creating Table events_d134
data/ball-events\VAS\ARN\y1\d214\ball_events.csv
Creating Table events_d214
data/ball-events\VAS\ARN\y1\d216\ball_events.csv
Creating Table events_d216
data/ball-events\VAS\BKO\y1\d144\ball_events.csv
Creating Table events_d144
data/ball-events\VAS\BKO\y1\d145\ball_events.csv
Creating Table events_d145
data/ball-events\VAS\BXH\y1\d115\ball_events.csv
Creating Table events_d115
data/ball-events\VAS\BXH\y1\d116\ball_events.csv
Creating Table events_d116
data/ball-events\VAS\BXH\y1\d117\ball_events.csv
Creating Table events_d117
data/ball-events\VAS\GJP\y1\d188\ball_events.csv
Creating Table events_d188
data/ball-events\VAS\GJP\y1\d189\ball_events.csv
Creating Table events_d189
data/ball-events\VAS\GJP\y1\d190\ball_events.csv
Creating Table events_d190
data/ball-events\VAS\IOL\y1\d121\ball_events.csv
Creating Table events_d121
data/ball-events\VAS\IOL\y1\d122\ball_events.csv
Creating Table events_d122
data/ball-events\VAS\IOL\y1\d123\ball_events.csv
Creating Table events_d123
data/ball-events\VAS\JGO\y1\d198\ball_events.csv
Creating Table events_d198
data/ball-events\VAS\JGO\y1\d199\ball_events.csv
Creating Table events_d199
data/ball-events\VAS\JGO\y1\d200\ball_events.csv
Creating Table events_d200
data/ball-events\VAS\JGO\y1\d201\ball_events.csv
Creating Table events_d201
data/ball-events\VAS\KVN\y1\d142\ball_events.csv
Creating Table events_d142
data/ball-events\VAS\KVN\y1\d143\ball_events.csv
Creating Table events_d143
data/ball-events\VAS\KZR\y1\d159\ball_events.csv
Creating Table events_d159
data/ball-events\VAS\KZR\y1\d160\ball_events.csv
Creating Table events_d160
data/ball-events\VAS\KZR\y1\d161\ball_events.csv
Creating Table events_d161
data/ball-events\VAS\KZR\y1\d162\ball_events.csv
Creating Table events_d162
data/ball-events\VAS\MSN\y1\d104\ball_events.csv
Creating Table events_d104
data/ball-events\VAS\MSN\y1\d105\ball_events.csv
Creating Table events_d105
data/ball-events\VAS\MSN\y1\d106\ball_events.csv
Creating Table events_d106
data/ball-events\VAS\MTW\y1\d174\ball_events.csv
Creating Table events_d174
data/ball-events\VAS\MTW\y1\d175\ball_events.csv
Creating Table events_d175
data/ball-events\VAS\MTW\y1\d176\ball_events.csv
Creating Table events_d176
data/ball-events\VAS\OSW\y1\d086\ball_events.csv
Creating Table events_d086
data/ball-events\VAS\OSW\y1\d087\ball_events.csv
Creating Table events_d087
data/ball-events\VAS\OSW\y1\d088\ball_events.csv
Creating Table events_d088
data/ball-events\VAS\OWV\y1\d171\ball_events.csv
Creating Table events_d171
data/ball-events\VAS\OWV\y1\d172\ball_events.csv
Creating Table events_d172
data/ball-events\VAS\OWV\y1\d173\ball_events.csv
Creating Table events_d173
data/ball-events\VAS\PHD\y1\d077\ball_events.csv
Creating Table events_d077
data/ball-events\VAS\PHD\y1\d077.5\ball_events.csv
Creating Table events_d077_5
data/ball-events\VAS\PHD\y1\d078\ball_events.csv
Creating Table events_d078
data/ball-events\VAS\PHD\y1\d089\ball_events.csv
Creating Table events_d089
data/ball-events\VAS\PHD\y1\d090\ball_events.csv
Creating Table events_d090
data/ball-events\VAS\PHD\y1\d091\ball_events.csv
Creating Table events_d091
data/ball-events\VAS\PHD\y1\d092\ball_events.csv
Creating Table events_d092
data/ball-events\VAS\PHD\y1\d093\ball_events.csv
Creating Table events_d093
data/ball-events\VAS\PHD\y1\d202\ball_events.csv
Creating Table events_d202
data/ball-events\VAS\PHD\y1\d203\ball_events.csv
Creating Table events_d203
data/ball-events\VAS\PHD\y1\d204\ball_events.csv
Creating Table events_d204
data/ball-events\VAS\PHD\y1\d209\ball_events.csv
Creating Table events_d209
data/ball-events\VAS\PHD\y1\d210\ball_events.csv
Creating Table events_d210
data/ball-events\VAS\PHD\y1\d211\ball_events.csv
Creating Table events_d211
data/ball-events\VAS\PHD\y1\d212\ball_events.csv
Creating Table events_d212
data/ball-events\VAS\RRM\y1\d185\ball_events.csv
Creating Table events_d185
data/ball-events\VAS\RRM\y1\d186\ball_events.csv
Creating Table events_d186
data/ball-events\VAS\RRM\y1\d187\ball_events.csv
Creating Table events_d187
data/ball-events\VAS\VNG\y1\d149\ball_events.csv
Creating Table events_d149
data/ball-events\VAS\VNG\y1\d150\ball_events.csv
Creating Table events_d150
data/ball-events\VAS\VNG\y1\d151\ball_events.csv
Creating Table events_d151
data/ball-events\VAS\WDF\y1\d129\ball_events.csv
Creating Table events_d129
data/ball-events\VAS\WDF\y1\d130\ball_events.csv
Creating Table events_d130
data/ball-events\VAS\WDF\y1\d131\ball_events.csv
Creating Table events_d131
data/ball-events\VAS\WTH\y1\d101\ball_events.csv
Creating Table events_d101
data/ball-events\VAS\WTH\y1\d102\ball_events.csv
Creating Table events_d102
data/ball-events\VAS\WTH\y1\d103\ball_events.csv
Creating Table events_d103

In [ ]:
ball_positions_names = []
for file in glob.glob("data/ball-positions/*/*/*/*/*.csv"):
    print(file)
    df = pd.read_csv(file)
    print("Creating Table", f'ball_positions_{file[31:-19].replace(".5","_5")}')
    ball_positions_names.append(f'ball_positions_{file[31:-19].replace(".5","_5")}')
    df.to_sql(f'ball_positions_{file[31:-19].replace(".5","_5")}', conn, if_exists="replace", index=False)

data/ball-positions\ANI\ADQ\y1\d143\ball-positions.csv
Creating Table ball_positions_d143
data/ball-positions\ANI\ADQ\y1\d144\ball-positions.csv
Creating Table ball_positions_d144
data/ball-positions\ANI\ADQ\y1\d145\ball-positions.csv
Creating Table ball_positions_d145
data/ball-positions\ANI\ADQ\y1\d146\ball-positions.csv
Creating Table ball_positions_d146
data/ball-positions\ANI\EMB\y1\d167\ball-positions.csv
Creating Table ball_positions_d167
data/ball-positions\ANI\EMB\y1\d168\ball-positions.csv
Creating Table ball_positions_d168
data/ball-positions\ANI\EMB\y1\d169\ball-positions.csv
Creating Table ball_positions_d169
data/ball-positions\ANI\FET\y1\d178\ball-positions.csv
Creating Table ball_positions_d178
data/ball-positions\ANI\FET\y1\d179\ball-positions.csv
Creating Table ball_positions_d179
data/ball-positions\ANI\FET\y1\d180\ball-positions.csv
Creating Table ball_positions_d180
data/ball-positions\ANI\FXP\y1\d194\ball-positions.csv
Creating Table ball_positions_d194
data/ball-positions\ANI\FXP\y1\d195\ball-positions.csv
Creating Table ball_positions_d195
data/ball-positions\ANI\FXP\y1\d196\ball-positions.csv
Creating Table ball_positions_d196
data/ball-positions\ANI\FXP\y1\d197\ball-positions.csv
Creating Table ball_positions_d197
data/ball-positions\ANI\IGL\y1\d171\ball-positions.csv
Creating Table ball_positions_d171
data/ball-positions\ANI\IGL\y1\d172\ball-positions.csv
Creating Table ball_positions_d172
data/ball-positions\ANI\IGL\y1\d173\ball-positions.csv
Creating Table ball_positions_d173
data/ball-positions\ANI\JPB\y1\d112\ball-positions.csv
Creating Table ball_positions_d112
data/ball-positions\ANI\JPB\y1\d113\ball-positions.csv
Creating Table ball_positions_d113
data/ball-positions\ANI\JPB\y1\d114\ball-positions.csv
Creating Table ball_positions_d114
data/ball-positions\ANI\JPB\y1\d115\ball-positions.csv
Creating Table ball_positions_d115
data/ball-positions\ANI\MEX\y1\d125\ball-positions.csv
Creating Table ball_positions_d125
data/ball-positions\ANI\MEX\y1\d126\ball-positions.csv
Creating Table ball_positions_d126
data/ball-positions\ANI\MEX\y1\d127\ball-positions.csv
Creating Table ball_positions_d127
data/ball-positions\ANI\MEX\y1\d128\ball-positions.csv
Creating Table ball_positions_d128
data/ball-positions\ANI\MSE\y1\d122\ball-positions.csv
Creating Table ball_positions_d122
data/ball-positions\ANI\MSE\y1\d123\ball-positions.csv
Creating Table ball_positions_d123
data/ball-positions\ANI\MSE\y1\d124\ball-positions.csv
Creating Table ball_positions_d124
data/ball-positions\ANI\NLG\y1\d067.5\ball-positions.csv
Creating Table ball_positions_d067_5
data/ball-positions\ANI\OER\y1\d105\ball-positions.csv
Creating Table ball_positions_d105
data/ball-positions\ANI\OER\y1\d105.5\ball-positions.csv
Creating Table ball_positions_d105_5
data/ball-positions\ANI\OER\y1\d106\ball-positions.csv
Creating Table ball_positions_d106
data/ball-positions\ANI\OER\y1\d106.5\ball-positions.csv
Creating Table ball_positions_d106_5
data/ball-positions\ANI\OER\y1\d107\ball-positions.csv
Creating Table ball_positions_d107
data/ball-positions\ANI\QBR\y1\d138\ball-positions.csv
Creating Table ball_positions_d138
data/ball-positions\ANI\QBR\y1\d139\ball-positions.csv
Creating Table ball_positions_d139
data/ball-positions\ANI\QBR\y1\d140\ball-positions.csv
Creating Table ball_positions_d140
data/ball-positions\ANI\QBR\y1\d141\ball-positions.csv
Creating Table ball_positions_d141
data/ball-positions\ANI\QHX\y1\d209\ball-positions.csv
Creating Table ball_positions_d209
data/ball-positions\ANI\QHX\y1\d210\ball-positions.csv
Creating Table ball_positions_d210
data/ball-positions\ANI\QHX\y1\d211\ball-positions.csv
Creating Table ball_positions_d211
data/ball-positions\ANI\QHX\y1\d212\ball-positions.csv
Creating Table ball_positions_d212
data/ball-positions\ANI\SZJ\y1\d163\ball-positions.csv
Creating Table ball_positions_d163
data/ball-positions\ANI\SZJ\y1\d164\ball-positions.csv
Creating Table ball_positions_d164
data/ball-positions\ANI\SZJ\y1\d164.5\ball-positions.csv
Creating Table ball_positions_d164_5
data/ball-positions\ANI\SZJ\y1\d165\ball-positions.csv
Creating Table ball_positions_d165
data/ball-positions\ANI\SZJ\y1\d166\ball-positions.csv
Creating Table ball_positions_d166
data/ball-positions\ANI\WIF\y1\d181\ball-positions.csv
Creating Table ball_positions_d181
data/ball-positions\ANI\WIF\y1\d182\ball-positions.csv
Creating Table ball_positions_d182
data/ball-positions\ANI\WIF\y1\d183\ball-positions.csv
Creating Table ball_positions_d183
data/ball-positions\ANI\WIF\y1\d184\ball-positions.csv
Creating Table ball_positions_d184
data/ball-positions\ARN\AIP\y1\d074\ball-positions.csv
Creating Table ball_positions_d074
data/ball-positions\ARN\AIP\y1\d074.5\ball-positions.csv
Creating Table ball_positions_d074_5
data/ball-positions\ARN\ALC\y1\d144\ball-positions.csv
Creating Table ball_positions_d144
data/ball-positions\ARN\ALC\y1\d145\ball-positions.csv
Creating Table ball_positions_d145
data/ball-positions\ARN\AVV\y1\d177\ball-positions.csv
Creating Table ball_positions_d177
data/ball-positions\ARN\AVV\y1\d178\ball-positions.csv
Creating Table ball_positions_d178
data/ball-positions\ARN\BTL\y1\d167\ball-positions.csv
Creating Table ball_positions_d167
data/ball-positions\ARN\BTL\y1\d168\ball-positions.csv
Creating Table ball_positions_d168
data/ball-positions\ARN\BTL\y1\d169\ball-positions.csv
Creating Table ball_positions_d169
data/ball-positions\ARN\EXB\y1\d136\ball-positions.csv
Creating Table ball_positions_d136
data/ball-positions\ARN\EXB\y1\d137\ball-positions.csv
Creating Table ball_positions_d137
data/ball-positions\ARN\EXB\y1\d138\ball-positions.csv
Creating Table ball_positions_d138
data/ball-positions\ARN\FSD\y1\d104.5\ball-positions.csv
Creating Table ball_positions_d104_5
data/ball-positions\ARN\HNO\y1\d213\ball-positions.csv
Creating Table ball_positions_d213
data/ball-positions\ARN\KTT\y1\d116\ball-positions.csv
Creating Table ball_positions_d116
data/ball-positions\ARN\KTT\y1\d116.5\ball-positions.csv
Creating Table ball_positions_d116_5
data/ball-positions\ARN\LRQ\y1\d181\ball-positions.csv
Creating Table ball_positions_d181
data/ball-positions\ARN\LRQ\y1\d182\ball-positions.csv
Creating Table ball_positions_d182
data/ball-positions\ARN\LRQ\y1\d183\ball-positions.csv
Creating Table ball_positions_d183
data/ball-positions\ARN\MKS\y1\d118\ball-positions.csv
Creating Table ball_positions_d118
data/ball-positions\ARN\MKS\y1\d119\ball-positions.csv
Creating Table ball_positions_d119
data/ball-positions\ARN\MKS\y1\d120\ball-positions.csv
Creating Table ball_positions_d120
data/ball-positions\ARN\NWM\y1\d125\ball-positions.csv
Creating Table ball_positions_d125
data/ball-positions\ARN\NWM\y1\d126\ball-positions.csv
Creating Table ball_positions_d126
data/ball-positions\ARN\NWM\y1\d127\ball-positions.csv
Creating Table ball_positions_d127
data/ball-positions\ARN\NWM\y1\d127.5\ball-positions.csv
Creating Table ball_positions_d127_5
data/ball-positions\ARN\NXS\y1\d083\ball-positions.csv
Creating Table ball_positions_d083
data/ball-positions\ARN\NXS\y1\d084\ball-positions.csv
Creating Table ball_positions_d084
data/ball-positions\ARN\NYN\y1\d097\ball-positions.csv
Creating Table ball_positions_d097
data/ball-positions\ARN\NYN\y1\d098\ball-positions.csv
Creating Table ball_positions_d098
data/ball-positions\ARN\PHD\y1\d188\ball-positions.csv
Creating Table ball_positions_d188
data/ball-positions\ARN\PHD\y1\d189\ball-positions.csv
Creating Table ball_positions_d189
data/ball-positions\ARN\PHD\y1\d190\ball-positions.csv
Creating Table ball_positions_d190
data/ball-positions\ARN\PWH\y1\d209\ball-positions.csv
Creating Table ball_positions_d209
data/ball-positions\ARN\PWH\y1\d210\ball-positions.csv
Creating Table ball_positions_d210
data/ball-positions\ARN\PWH\y1\d211\ball-positions.csv
Creating Table ball_positions_d211
data/ball-positions\ARN\PWH\y1\d212\ball-positions.csv
Creating Table ball_positions_d212
data/ball-positions\ARN\RME\y1\d152\ball-positions.csv
Creating Table ball_positions_d152
data/ball-positions\ARN\RME\y1\d153\ball-positions.csv
Creating Table ball_positions_d153
data/ball-positions\ARN\RME\y1\d153.5\ball-positions.csv
Creating Table ball_positions_d153_5
data/ball-positions\ARN\SQF\y1\d068\ball-positions.csv
Creating Table ball_positions_d068
data/ball-positions\ARN\SQF\y1\d069\ball-positions.csv
Creating Table ball_positions_d069
data/ball-positions\ARN\SQF\y1\d070\ball-positions.csv
Creating Table ball_positions_d070
data/ball-positions\ARN\SQF\y1\d071\ball-positions.csv
Creating Table ball_positions_d071
data/ball-positions\ARN\TDW\y1\d185\ball-positions.csv
Creating Table ball_positions_d185
data/ball-positions\ARN\TDW\y1\d186\ball-positions.csv
Creating Table ball_positions_d186
data/ball-positions\ARN\TDW\y1\d187\ball-positions.csv
Creating Table ball_positions_d187
data/ball-positions\ARN\TES\y1\d198\ball-positions.csv
Creating Table ball_positions_d198
data/ball-positions\ARN\TES\y1\d199\ball-positions.csv
Creating Table ball_positions_d199
data/ball-positions\ARN\TES\y1\d200\ball-positions.csv
Creating Table ball_positions_d200
data/ball-positions\ARN\TES\y1\d201\ball-positions.csv
Creating Table ball_positions_d201
data/ball-positions\ARN\THF\y1\d108\ball-positions.csv
Creating Table ball_positions_d108
data/ball-positions\ARN\THF\y1\d109\ball-positions.csv
Creating Table ball_positions_d109
data/ball-positions\ARN\THF\y1\d110\ball-positions.csv
Creating Table ball_positions_d110
data/ball-positions\ARN\URD\y1\d072\ball-positions.csv
Creating Table ball_positions_d072
data/ball-positions\ARN\VAS\y1\d139\ball-positions.csv
Creating Table ball_positions_d139
data/ball-positions\ARN\VAS\y1\d140\ball-positions.csv
Creating Table ball_positions_d140
data/ball-positions\ARN\VAS\y1\d141\ball-positions.csv
Creating Table ball_positions_d141
data/ball-positions\ARN\VAS\y1\d217\ball-positions.csv
Creating Table ball_positions_d217
data/ball-positions\ARN\WLI\y1\d094\ball-positions.csv
Creating Table ball_positions_d094
data/ball-positions\ARN\WLI\y1\d095\ball-positions.csv
Creating Table ball_positions_d095
data/ball-positions\ARN\WLI\y1\d096\ball-positions.csv
Creating Table ball_positions_d096
data/ball-positions\ARN\XOZ\y1\d155\ball-positions.csv
Creating Table ball_positions_d155
data/ball-positions\ARN\XOZ\y1\d155.5\ball-positions.csv
Creating Table ball_positions_d155_5
data/ball-positions\ARN\ZGC\y1\d086\ball-positions.csv
Creating Table ball_positions_d086
data/ball-positions\ARN\ZGC\y1\d087\ball-positions.csv
Creating Table ball_positions_d087
data/ball-positions\ARN\ZGC\y1\d088\ball-positions.csv
Creating Table ball_positions_d088
data/ball-positions\ARN\ZGC\y1\d089\ball-positions.csv
Creating Table ball_positions_d089
data/ball-positions\PHD\ARN\y1\d195\ball-positions.csv
Creating Table ball_positions_d195
data/ball-positions\PHD\ARN\y1\d196\ball-positions.csv
Creating Table ball_positions_d196
data/ball-positions\PHD\ARN\y1\d197\ball-positions.csv
Creating Table ball_positions_d197
data/ball-positions\PHD\ATL\y1\d205\ball-positions.csv
Creating Table ball_positions_d205
data/ball-positions\PHD\ATL\y1\d206\ball-positions.csv
Creating Table ball_positions_d206
data/ball-positions\PHD\ATL\y1\d207\ball-positions.csv
Creating Table ball_positions_d207
data/ball-positions\PHD\ATL\y1\d208\ball-positions.csv
Creating Table ball_positions_d208
data/ball-positions\PHD\CYU\y1\d097\ball-positions.csv
Creating Table ball_positions_d097
data/ball-positions\PHD\CYU\y1\d098\ball-positions.csv
Creating Table ball_positions_d098
data/ball-positions\PHD\CYU\y1\d099\ball-positions.csv
Creating Table ball_positions_d099
data/ball-positions\PHD\FNQ\y1\d163\ball-positions.csv
Creating Table ball_positions_d163
data/ball-positions\PHD\FNQ\y1\d164\ball-positions.csv
Creating Table ball_positions_d164
data/ball-positions\PHD\FNQ\y1\d165\ball-positions.csv
Creating Table ball_positions_d165
data/ball-positions\PHD\FNQ\y1\d166\ball-positions.csv
Creating Table ball_positions_d166
data/ball-positions\PHD\GNX\y1\d139\ball-positions.csv
Creating Table ball_positions_d139
data/ball-positions\PHD\GNX\y1\d140\ball-positions.csv
Creating Table ball_positions_d140
data/ball-positions\PHD\GNX\y1\d141\ball-positions.csv
Creating Table ball_positions_d141
data/ball-positions\PHD\HYG\y1\d136\ball-positions.csv
Creating Table ball_positions_d136
data/ball-positions\PHD\HYG\y1\d137\ball-positions.csv
Creating Table ball_positions_d137
data/ball-positions\PHD\HYG\y1\d138\ball-positions.csv
Creating Table ball_positions_d138
data/ball-positions\PHD\JJP\y1\d080\ball-positions.csv
Creating Table ball_positions_d080
data/ball-positions\PHD\JJP\y1\d081\ball-positions.csv
Creating Table ball_positions_d081
data/ball-positions\PHD\JJP\y1\d082\ball-positions.csv
Creating Table ball_positions_d082
data/ball-positions\PHD\MPC\y1\d167\ball-positions.csv
Creating Table ball_positions_d167
data/ball-positions\PHD\MPC\y1\d168\ball-positions.csv
Creating Table ball_positions_d168
data/ball-positions\PHD\MPC\y1\d169\ball-positions.csv
Creating Table ball_positions_d169
data/ball-positions\PHD\NFP\y1\d094\ball-positions.csv
Creating Table ball_positions_d094
data/ball-positions\PHD\NFP\y1\d095\ball-positions.csv
Creating Table ball_positions_d095
data/ball-positions\PHD\NFP\y1\d096\ball-positions.csv
Creating Table ball_positions_d096
data/ball-positions\PHD\RYU\y1\d083\ball-positions.csv
Creating Table ball_positions_d083
data/ball-positions\PHD\RYU\y1\d084\ball-positions.csv
Creating Table ball_positions_d084
data/ball-positions\PHD\RYU\y1\d085\ball-positions.csv
Creating Table ball_positions_d085
data/ball-positions\PHD\SPL\y1\d108\ball-positions.csv
Creating Table ball_positions_d108
data/ball-positions\PHD\SPL\y1\d109\ball-positions.csv
Creating Table ball_positions_d109
data/ball-positions\PHD\SPL\y1\d110\ball-positions.csv
Creating Table ball_positions_d110
data/ball-positions\PHD\TQS\y1\d181\ball-positions.csv
Creating Table ball_positions_d181
data/ball-positions\PHD\TQS\y1\d182\ball-positions.csv
Creating Table ball_positions_d182
data/ball-positions\PHD\VAS\y1\d065\ball-positions.csv
Creating Table ball_positions_d065
data/ball-positions\PHD\VAS\y1\d066\ball-positions.csv
Creating Table ball_positions_d066
data/ball-positions\PHD\VAS\y1\d124\ball-positions.csv
Creating Table ball_positions_d124
data/ball-positions\PHD\VAS\y1\d125\ball-positions.csv
Creating Table ball_positions_d125
data/ball-positions\PHD\VAS\y1\d127\ball-positions.csv
Creating Table ball_positions_d127
data/ball-positions\PHD\VAS\y1\d152\ball-positions.csv
Creating Table ball_positions_d152
data/ball-positions\PHD\VAS\y1\d153\ball-positions.csv
Creating Table ball_positions_d153
data/ball-positions\PHD\VAS\y1\d153.5\ball-positions.csv
Creating Table ball_positions_d153_5
data/ball-positions\PHD\VAS\y1\d154\ball-positions.csv
Creating Table ball_positions_d154
data/ball-positions\PHD\VAS\y1\d155\ball-positions.csv
Creating Table ball_positions_d155
data/ball-positions\PHD\VAS\y1\d177\ball-positions.csv
Creating Table ball_positions_d177
data/ball-positions\PHD\VAS\y1\d178\ball-positions.csv
Creating Table ball_positions_d178
data/ball-positions\PHD\VHA\y1\d146\ball-positions.csv
Creating Table ball_positions_d146
data/ball-positions\PHD\VHA\y1\d147\ball-positions.csv
Creating Table ball_positions_d147
data/ball-positions\PHD\VHA\y1\d148\ball-positions.csv
Creating Table ball_positions_d148
data/ball-positions\PHD\VKA\y1\d061\ball-positions.csv
Creating Table ball_positions_d061
data/ball-positions\PHD\VKA\y1\d062\ball-positions.csv
Creating Table ball_positions_d062
data/ball-positions\PHD\VKA\y1\d063\ball-positions.csv
Creating Table ball_positions_d063
data/ball-positions\PHD\VKA\y1\d064\ball-positions.csv
Creating Table ball_positions_d064
data/ball-positions\PHD\XGM\y1\d111\ball-positions.csv
Creating Table ball_positions_d111
data/ball-positions\PHD\XGM\y1\d112\ball-positions.csv
Creating Table ball_positions_d112
data/ball-positions\PHD\XGM\y1\d113\ball-positions.csv
Creating Table ball_positions_d113
data/ball-positions\PHD\XGM\y1\d114\ball-positions.csv
Creating Table ball_positions_d114
data/ball-positions\PHD\XPO\y1\d072\ball-positions.csv
Creating Table ball_positions_d072
data/ball-positions\PHD\XPO\y1\d073\ball-positions.csv
Creating Table ball_positions_d073
data/ball-positions\PHD\XPO\y1\d074\ball-positions.csv
Creating Table ball_positions_d074
data/ball-positions\PHD\XPO\y1\d075\ball-positions.csv
Creating Table ball_positions_d075
data/ball-positions\PHD\YXL\y1\d179\ball-positions.csv
Creating Table ball_positions_d179
data/ball-positions\PHD\YXL\y1\d180\ball-positions.csv
Creating Table ball_positions_d180
data/ball-positions\VAS\ARN\y1\d132\ball-positions.csv
Creating Table ball_positions_d132
data/ball-positions\VAS\ARN\y1\d133\ball-positions.csv
Creating Table ball_positions_d133
data/ball-positions\VAS\ARN\y1\d134\ball-positions.csv
Creating Table ball_positions_d134
data/ball-positions\VAS\ARN\y1\d214\ball-positions.csv
Creating Table ball_positions_d214
data/ball-positions\VAS\ARN\y1\d216\ball-positions.csv
Creating Table ball_positions_d216
data/ball-positions\VAS\BKO\y1\d144\ball-positions.csv
Creating Table ball_positions_d144
data/ball-positions\VAS\BKO\y1\d145\ball-positions.csv
Creating Table ball_positions_d145
data/ball-positions\VAS\BXH\y1\d115\ball-positions.csv
Creating Table ball_positions_d115
data/ball-positions\VAS\BXH\y1\d116\ball-positions.csv
Creating Table ball_positions_d116
data/ball-positions\VAS\BXH\y1\d117\ball-positions.csv
Creating Table ball_positions_d117
data/ball-positions\VAS\GJP\y1\d188\ball-positions.csv
Creating Table ball_positions_d188
data/ball-positions\VAS\GJP\y1\d189\ball-positions.csv
Creating Table ball_positions_d189
data/ball-positions\VAS\GJP\y1\d190\ball-positions.csv
Creating Table ball_positions_d190
data/ball-positions\VAS\IOL\y1\d121\ball-positions.csv
Creating Table ball_positions_d121
data/ball-positions\VAS\IOL\y1\d122\ball-positions.csv
Creating Table ball_positions_d122
data/ball-positions\VAS\IOL\y1\d123\ball-positions.csv
Creating Table ball_positions_d123
data/ball-positions\VAS\JGO\y1\d198\ball-positions.csv
Creating Table ball_positions_d198
data/ball-positions\VAS\JGO\y1\d199\ball-positions.csv
Creating Table ball_positions_d199
data/ball-positions\VAS\JGO\y1\d200\ball-positions.csv
Creating Table ball_positions_d200
data/ball-positions\VAS\JGO\y1\d201\ball-positions.csv
Creating Table ball_positions_d201
data/ball-positions\VAS\KVN\y1\d142\ball-positions.csv
Creating Table ball_positions_d142
data/ball-positions\VAS\KVN\y1\d143\ball-positions.csv
Creating Table ball_positions_d143
data/ball-positions\VAS\KZR\y1\d159\ball-positions.csv
Creating Table ball_positions_d159
data/ball-positions\VAS\KZR\y1\d160\ball-positions.csv
Creating Table ball_positions_d160
data/ball-positions\VAS\KZR\y1\d161\ball-positions.csv
Creating Table ball_positions_d161
data/ball-positions\VAS\KZR\y1\d162\ball-positions.csv
Creating Table ball_positions_d162
data/ball-positions\VAS\MSN\y1\d104\ball-positions.csv
Creating Table ball_positions_d104
data/ball-positions\VAS\MSN\y1\d105\ball-positions.csv
Creating Table ball_positions_d105
data/ball-positions\VAS\MSN\y1\d106\ball-positions.csv
Creating Table ball_positions_d106
data/ball-positions\VAS\MTW\y1\d174\ball-positions.csv
Creating Table ball_positions_d174
data/ball-positions\VAS\MTW\y1\d175\ball-positions.csv
Creating Table ball_positions_d175
data/ball-positions\VAS\MTW\y1\d176\ball-positions.csv
Creating Table ball_positions_d176
data/ball-positions\VAS\OSW\y1\d086\ball-positions.csv
Creating Table ball_positions_d086
data/ball-positions\VAS\OSW\y1\d087\ball-positions.csv
Creating Table ball_positions_d087
data/ball-positions\VAS\OSW\y1\d088\ball-positions.csv
Creating Table ball_positions_d088
data/ball-positions\VAS\OWV\y1\d171\ball-positions.csv
Creating Table ball_positions_d171
data/ball-positions\VAS\OWV\y1\d172\ball-positions.csv

In [ ]:
player_positions_names = []
for file in glob.glob("data/player-positions/*/*/*/*/*.csv"):
    print(file)
    df = pd.read_csv(file)
    print("Creating Table", f'player_positions_{file[33:-21].replace(".5","_5")}')
    player_positions_names.append(f'player_positions_{file[33:-21].replace(".5","_5")}')
    df.to_sql(f'player_positions_{file[33:-21].replace(".5","_5")}', conn, if_exists="replace", index=False)

data/player-positions\ANI\ADQ\y1\d143\player-positions.csv
Creating Table player_positions_d143
data/player-positions\ANI\ADQ\y1\d144\player-positions.csv
Creating Table player_positions_d144
data/player-positions\ANI\ADQ\y1\d145\player-positions.csv
Creating Table player_positions_d145
data/player-positions\ANI\ADQ\y1\d146\player-positions.csv
Creating Table player_positions_d146
data/player-positions\ANI\EMB\y1\d167\player-positions.csv
Creating Table player_positions_d167
data/player-positions\ANI\EMB\y1\d168\player-positions.csv
Creating Table player_positions_d168
data/player-positions\ANI\EMB\y1\d169\player-positions.csv
Creating Table player_positions_d169
data/player-positions\ANI\FET\y1\d178\player-positions.csv
Creating Table player_positions_d178
data/player-positions\ANI\FET\y1\d179\player-positions.csv
Creating Table player_positions_d179
data/player-positions\ANI\FET\y1\d180\player-positions.csv
Creating Table player_positions_d180
data/player-positions\ANI\FXP\y1\d194\player-positions.csv
Creating Table player_positions_d194
data/player-positions\ANI\FXP\y1\d195\player-positions.csv
Creating Table player_positions_d195
data/player-positions\ANI\FXP\y1\d196\player-positions.csv
Creating Table player_positions_d196
data/player-positions\ANI\FXP\y1\d197\player-positions.csv
Creating Table player_positions_d197
data/player-positions\ANI\IGL\y1\d171\player-positions.csv
Creating Table player_positions_d171
data/player-positions\ANI\IGL\y1\d172\player-positions.csv
Creating Table player_positions_d172
data/player-positions\ANI\IGL\y1\d173\player-positions.csv
Creating Table player_positions_d173
data/player-positions\ANI\JPB\y1\d112\player-positions.csv
Creating Table player_positions_d112
data/player-positions\ANI\JPB\y1\d113\player-positions.csv
Creating Table player_positions_d113
data/player-positions\ANI\JPB\y1\d114\player-positions.csv
Creating Table player_positions_d114
data/player-positions\ANI\JPB\y1\d115\player-positions.csv
Creating Table player_positions_d115
data/player-positions\ANI\MEX\y1\d125\player-positions.csv
Creating Table player_positions_d125
data/player-positions\ANI\MEX\y1\d126\player-positions.csv
Creating Table player_positions_d126
data/player-positions\ANI\MEX\y1\d127\player-positions.csv
Creating Table player_positions_d127
data/player-positions\ANI\MEX\y1\d128\player-positions.csv
Creating Table player_positions_d128
data/player-positions\ANI\MSE\y1\d122\player-positions.csv
Creating Table player_positions_d122
data/player-positions\ANI\MSE\y1\d123\player-positions.csv
Creating Table player_positions_d123
data/player-positions\ANI\MSE\y1\d124\player-positions.csv
Creating Table player_positions_d124
data/player-positions\ANI\NLG\y1\d067.5\player-positions.csv
Creating Table player_positions_d067_5
data/player-positions\ANI\OER\y1\d105\player-positions.csv
Creating Table player_positions_d105
data/player-positions\ANI\OER\y1\d105.5\player-positions.csv
Creating Table player_positions_d105_5
data/player-positions\ANI\OER\y1\d106\player-positions.csv
Creating Table player_positions_d106
data/player-positions\ANI\OER\y1\d106.5\player-positions.csv
Creating Table player_positions_d106_5
data/player-positions\ANI\OER\y1\d107\player-positions.csv
Creating Table player_positions_d107
data/player-positions\ANI\QBR\y1\d138\player-positions.csv
Creating Table player_positions_d138
data/player-positions\ANI\QBR\y1\d139\player-positions.csv
Creating Table player_positions_d139
data/player-positions\ANI\QBR\y1\d140\player-positions.csv
Creating Table player_positions_d140
data/player-positions\ANI\QBR\y1\d141\player-positions.csv
Creating Table player_positions_d141
data/player-positions\ANI\QHX\y1\d209\player-positions.csv
Creating Table player_positions_d209
data/player-positions\ANI\QHX\y1\d210\player-positions.csv
Creating Table player_positions_d210
data/player-positions\ANI\QHX\y1\d211\player-positions.csv
Creating Table player_positions_d211
data/player-positions\ANI\QHX\y1\d212\player-positions.csv
Creating Table player_positions_d212
data/player-positions\ANI\SZJ\y1\d163\player-positions.csv
Creating Table player_positions_d163
data/player-positions\ANI\SZJ\y1\d164\player-positions.csv
Creating Table player_positions_d164
data/player-positions\ANI\SZJ\y1\d164.5\player-positions.csv
Creating Table player_positions_d164_5
data/player-positions\ANI\SZJ\y1\d165\player-positions.csv
Creating Table player_positions_d165
data/player-positions\ANI\SZJ\y1\d166\player-positions.csv
Creating Table player_positions_d166
data/player-positions\ANI\WIF\y1\d181\player-positions.csv
Creating Table player_positions_d181
data/player-positions\ANI\WIF\y1\d182\player-positions.csv
Creating Table player_positions_d182
data/player-positions\ANI\WIF\y1\d183\player-positions.csv
Creating Table player_positions_d183
data/player-positions\ANI\WIF\y1\d184\player-positions.csv
Creating Table player_positions_d184
data/player-positions\ARN\AIP\y1\d074\player-positions.csv
Creating Table player_positions_d074
data/player-positions\ARN\AIP\y1\d074.5\player-positions.csv
Creating Table player_positions_d074_5
data/player-positions\ARN\ALC\y1\d144\player-positions.csv
Creating Table player_positions_d144
data/player-positions\ARN\ALC\y1\d145\player-positions.csv
Creating Table player_positions_d145
data/player-positions\ARN\AVV\y1\d177\player-positions.csv
Creating Table player_positions_d177
data/player-positions\ARN\AVV\y1\d178\player-positions.csv
Creating Table player_positions_d178
data/player-positions\ARN\BTL\y1\d167\player-positions.csv
Creating Table player_positions_d167
data/player-positions\ARN\BTL\y1\d168\player-positions.csv
Creating Table player_positions_d168
data/player-positions\ARN\BTL\y1\d169\player-positions.csv
Creating Table player_positions_d169
data/player-positions\ARN\EXB\y1\d136\player-positions.csv
Creating Table player_positions_d136
data/player-positions\ARN\EXB\y1\d137\player-positions.csv
Creating Table player_positions_d137
data/player-positions\ARN\EXB\y1\d138\player-positions.csv
Creating Table player_positions_d138
data/player-positions\ARN\FSD\y1\d104.5\player-positions.csv
Creating Table player_positions_d104_5
data/player-positions\ARN\HNO\y1\d213\player-positions.csv
Creating Table player_positions_d213
data/player-positions\ARN\KTT\y1\d116\player-positions.csv
Creating Table player_positions_d116
data/player-positions\ARN\KTT\y1\d116.5\player-positions.csv
Creating Table player_positions_d116_5

C:\Users\Felto\AppData\Local\Temp\ipykernel_29584\149084967.py:4: DtypeWarning: Columns (0: game_string) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

data/player-positions\ARN\LRQ\y1\d181\player-positions.csv
Creating Table player_positions_d181
data/player-positions\ARN\LRQ\y1\d182\player-positions.csv
Creating Table player_positions_d182
data/player-positions\ARN\LRQ\y1\d183\player-positions.csv
Creating Table player_positions_d183
data/player-positions\ARN\MKS\y1\d118\player-positions.csv
Creating Table player_positions_d118
data/player-positions\ARN\MKS\y1\d119\player-positions.csv
Creating Table player_positions_d119
data/player-positions\ARN\MKS\y1\d120\player-positions.csv
Creating Table player_positions_d120
data/player-positions\ARN\NWM\y1\d125\player-positions.csv
Creating Table player_positions_d125
data/player-positions\ARN\NWM\y1\d126\player-positions.csv
Creating Table player_positions_d126
data/player-positions\ARN\NWM\y1\d127\player-positions.csv
Creating Table player_positions_d127
data/player-positions\ARN\NWM\y1\d127.5\player-positions.csv
Creating Table player_positions_d127_5
data/player-positions\ARN\NXS\y1\d083\player-positions.csv
Creating Table player_positions_d083
data/player-positions\ARN\NXS\y1\d084\player-positions.csv
Creating Table player_positions_d084
data/player-positions\ARN\NYN\y1\d097\player-positions.csv
Creating Table player_positions_d097
data/player-positions\ARN\NYN\y1\d098\player-positions.csv
Creating Table player_positions_d098
data/player-positions\ARN\PHD\y1\d188\player-positions.csv
Creating Table player_positions_d188
data/player-positions\ARN\PHD\y1\d189\player-positions.csv
Creating Table player_positions_d189
data/player-positions\ARN\PHD\y1\d190\player-positions.csv
Creating Table player_positions_d190
data/player-positions\ARN\PWH\y1\d209\player-positions.csv
Creating Table player_positions_d209
data/player-positions\ARN\PWH\y1\d210\player-positions.csv
Creating Table player_positions_d210
data/player-positions\ARN\PWH\y1\d211\player-positions.csv
Creating Table player_positions_d211
data/player-positions\ARN\PWH\y1\d212\player-positions.csv
Creating Table player_positions_d212
data/player-positions\ARN\RME\y1\d152\player-positions.csv
Creating Table player_positions_d152
data/player-positions\ARN\RME\y1\d153\player-positions.csv
Creating Table player_positions_d153
data/player-positions\ARN\RME\y1\d153.5\player-positions.csv
Creating Table player_positions_d153_5
data/player-positions\ARN\SQF\y1\d068\player-positions.csv
Creating Table player_positions_d068
data/player-positions\ARN\SQF\y1\d069\player-positions.csv
Creating Table player_positions_d069
data/player-positions\ARN\SQF\y1\d070\player-positions.csv
Creating Table player_positions_d070
data/player-positions\ARN\SQF\y1\d071\player-positions.csv
Creating Table player_positions_d071
data/player-positions\ARN\TDW\y1\d185\player-positions.csv
Creating Table player_positions_d185
data/player-positions\ARN\TDW\y1\d186\player-positions.csv
Creating Table player_positions_d186
data/player-positions\ARN\TDW\y1\d187\player-positions.csv
Creating Table player_positions_d187
data/player-positions\ARN\TES\y1\d198\player-positions.csv
Creating Table player_positions_d198
data/player-positions\ARN\TES\y1\d199\player-positions.csv
Creating Table player_positions_d199
data/player-positions\ARN\TES\y1\d200\player-positions.csv
Creating Table player_positions_d200
data/player-positions\ARN\TES\y1\d201\player-positions.csv
Creating Table player_positions_d201
data/player-positions\ARN\THF\y1\d108\player-positions.csv
Creating Table player_positions_d108
data/player-positions\ARN\THF\y1\d109\player-positions.csv
Creating Table player_positions_d109
data/player-positions\ARN\THF\y1\d110\player-positions.csv
Creating Table player_positions_d110
data/player-positions\ARN\URD\y1\d072\player-positions.csv
Creating Table player_positions_d072
data/player-positions\ARN\VAS\y1\d139\player-positions.csv
Creating Table player_positions_d139
data/player-positions\ARN\VAS\y1\d140\player-positions.csv
Creating Table player_positions_d140
data/player-positions\ARN\VAS\y1\d141\player-positions.csv
Creating Table player_positions_d141
data/player-positions\ARN\VAS\y1\d217\player-positions.csv
Creating Table player_positions_d217
data/player-positions\ARN\WLI\y1\d094\player-positions.csv
Creating Table player_positions_d094
data/player-positions\ARN\WLI\y1\d095\player-positions.csv
Creating Table player_positions_d095
data/player-positions\ARN\WLI\y1\d096\player-positions.csv
Creating Table player_positions_d096
data/player-positions\ARN\XOZ\y1\d155\player-positions.csv
Creating Table player_positions_d155
data/player-positions\ARN\XOZ\y1\d155.5\player-positions.csv
Creating Table player_positions_d155_5
data/player-positions\ARN\ZGC\y1\d086\player-positions.csv
Creating Table player_positions_d086
data/player-positions\ARN\ZGC\y1\d087\player-positions.csv
Creating Table player_positions_d087
data/player-positions\ARN\ZGC\y1\d088\player-positions.csv
Creating Table player_positions_d088
data/player-positions\ARN\ZGC\y1\d089\player-positions.csv
Creating Table player_positions_d089
data/player-positions\PHD\ARN\y1\d195\player-positions.csv
Creating Table player_positions_d195
data/player-positions\PHD\ARN\y1\d196\player-positions.csv
Creating Table player_positions_d196
data/player-positions\PHD\ARN\y1\d197\player-positions.csv
Creating Table player_positions_d197
data/player-positions\PHD\ATL\y1\d205\player-positions.csv
Creating Table player_positions_d205
data/player-positions\PHD\ATL\y1\d206\player-positions.csv
Creating Table player_positions_d206
data/player-positions\PHD\ATL\y1\d207\player-positions.csv
Creating Table player_positions_d207
data/player-positions\PHD\ATL\y1\d208\player-positions.csv
Creating Table player_positions_d208
data/player-positions\PHD\CYU\y1\d097\player-positions.csv
Creating Table player_positions_d097
data/player-positions\PHD\CYU\y1\d098\player-positions.csv
Creating Table player_positions_d098
data/player-positions\PHD\CYU\y1\d099\player-positions.csv
Creating Table player_positions_d099
data/player-positions\PHD\FNQ\y1\d163\player-positions.csv
Creating Table player_positions_d163
data/player-positions\PHD\FNQ\y1\d164\player-positions.csv
Creating Table player_positions_d164
data/player-positions\PHD\FNQ\y1\d165\player-positions.csv
Creating Table player_positions_d165
data/player-positions\PHD\FNQ\y1\d166\player-positions.csv
Creating Table player_positions_d166
data/player-positions\PHD\GNX\y1\d139\player-positions.csv
Creating Table player_positions_d139
data/player-positions\PHD\GNX\y1\d140\player-positions.csv
Creating Table player_positions_d140
data/player-positions\PHD\GNX\y1\d141\player-positions.csv
Creating Table player_positions_d141
data/player-positions\PHD\HYG\y1\d136\player-positions.csv
Creating Table player_positions_d136
data/player-positions\PHD\HYG\y1\d137\player-positions.csv
Creating Table player_positions_d137
data/player-positions\PHD\HYG\y1\d138\player-positions.csv
Creating Table player_positions_d138
data/player-positions\PHD\JJP\y1\d080\player-positions.csv
Creating Table player_positions_d080
data/player-positions\PHD\JJP\y1\d081\player-positions.csv
Creating Table player_positions_d081
data/player-positions\PHD\JJP\y1\d082\player-positions.csv
Creating Table player_positions_d082
data/player-positions\PHD\MPC\y1\d167\player-positions.csv
Creating Table player_positions_d167
data/player-positions\PHD\MPC\y1\d168\player-positions.csv
Creating Table player_positions_d168
data/player-positions\PHD\MPC\y1\d169\player-positions.csv
Creating Table player_positions_d169
data/player-positions\PHD\NFP\y1\d094\player-positions.csv
Creating Table player_positions_d094
data/player-positions\PHD\NFP\y1\d095\player-positions.csv
Creating Table player_positions_d095
data/player-positions\PHD\NFP\y1\d096\player-positions.csv
Creating Table player_positions_d096
data/player-positions\PHD\RYU\y1\d083\player-positions.csv
Creating Table player_positions_d083
data/player-positions\PHD\RYU\y1\d084\player-positions.csv
Creating Table player_positions_d084
data/player-positions\PHD\RYU\y1\d085\player-positions.csv
Creating Table player_positions_d085
data/player-positions\PHD\SPL\y1\d108\player-positions.csv
Creating Table player_positions_d108
data/player-positions\PHD\SPL\y1\d109\player-positions.csv
Creating Table player_positions_d109
data/player-positions\PHD\SPL\y1\d110\player-positions.csv
Creating Table player_positions_d110
data/player-positions\PHD\TQS\y1\d181\player-positions.csv
Creating Table player_positions_d181
data/player-positions\PHD\TQS\y1\d182\player-positions.csv
Creating Table player_positions_d182
data/player-positions\PHD\VAS\y1\d065\player-positions.csv
Creating Table player_positions_d065
data/player-positions\PHD\VAS\y1\d066\player-positions.csv
Creating Table player_positions_d066
data/player-positions\PHD\VAS\y1\d124\player-positions.csv
Creating Table player_positions_d124
data/player-positions\PHD\VAS\y1\d125\player-positions.csv
Creating Table player_positions_d125
data/player-positions\PHD\VAS\y1\d127\player-positions.csv
Creating Table player_positions_d127
data/player-positions\PHD\VAS\y1\d152\player-positions.csv
Creating Table player_positions_d152
data/player-positions\PHD\VAS\y1\d153\player-positions.csv
Creating Table player_positions_d153
data/player-positions\PHD\VAS\y1\d153.5\player-positions.csv
Creating Table player_positions_d153_5
data/player-positions\PHD\VAS\y1\d154\player-positions.csv
Creating Table player_positions_d154
data/player-positions\PHD\VAS\y1\d155\player-positions.csv
Creating Table player_positions_d155
data/player-positions\PHD\VAS\y1\d177\player-positions.csv
Creating Table player_positions_d177
data/player-positions\PHD\VAS\y1\d178\player-positions.csv
Creating Table player_positions_d178
data/player-positions\PHD\VHA\y1\d146\player-positions.csv
Creating Table player_positions_d146
data/player-positions\PHD\VHA\y1\d147\player-positions.csv
Creating Table player_positions_d147
data/player-positions\PHD\VHA\y1\d148\player-positions.csv

C:\Users\Felto\AppData\Local\Temp\ipykernel_29584\149084967.py:4: DtypeWarning: Columns (0: game_string) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Creating Table player_positions_d148
data/player-positions\PHD\VKA\y1\d061\player-positions.csv
Creating Table player_positions_d061
data/player-positions\PHD\VKA\y1\d062\player-positions.csv
Creating Table player_positions_d062
data/player-positions\PHD\VKA\y1\d063\player-positions.csv
Creating Table player_positions_d063
data/player-positions\PHD\VKA\y1\d064\player-positions.csv
Creating Table player_positions_d064
data/player-positions\PHD\XGM\y1\d111\player-positions.csv
Creating Table player_positions_d111
data/player-positions\PHD\XGM\y1\d112\player-positions.csv
Creating Table player_positions_d112
data/player-positions\PHD\XGM\y1\d113\player-positions.csv
Creating Table player_positions_d113
data/player-positions\PHD\XGM\y1\d114\player-positions.csv
Creating Table player_positions_d114
data/player-positions\PHD\XPO\y1\d072\player-positions.csv
Creating Table player_positions_d072
data/player-positions\PHD\XPO\y1\d073\player-positions.csv
Creating Table player_positions_d073
data/player-positions\PHD\XPO\y1\d074\player-positions.csv
Creating Table player_positions_d074
data/player-positions\PHD\XPO\y1\d075\player-positions.csv
Creating Table player_positions_d075
data/player-positions\PHD\YXL\y1\d179\player-positions.csv
Creating Table player_positions_d179
data/player-positions\PHD\YXL\y1\d180\player-positions.csv
Creating Table player_positions_d180
data/player-positions\VAS\ARN\y1\d132\player-positions.csv
Creating Table player_positions_d132
data/player-positions\VAS\ARN\y1\d133\player-positions.csv
Creating Table player_positions_d133
data/player-positions\VAS\ARN\y1\d134\player-positions.csv
Creating Table player_positions_d134
data/player-positions\VAS\ARN\y1\d214\player-positions.csv
Creating Table player_positions_d214
data/player-positions\VAS\ARN\y1\d216\player-positions.csv
Creating Table player_positions_d216
data/player-positions\VAS\BKO\y1\d144\player-positions.csv
Creating Table player_positions_d144
data/player-positions\VAS\BKO\y1\d145\player-positions.csv
Creating Table player_positions_d145
data/player-positions\VAS\BXH\y1\d115\player-positions.csv
Creating Table player_positions_d115
data/player-positions\VAS\BXH\y1\d116\player-positions.csv
Creating Table player_positions_d116
data/player-positions\VAS\BXH\y1\d117\player-positions.csv
Creating Table player_positions_d117
data/player-positions\VAS\GJP\y1\d188\player-positions.csv
Creating Table player_positions_d188
data/player-positions\VAS\GJP\y1\d189\player-positions.csv
Creating Table player_positions_d189
data/player-positions\VAS\GJP\y1\d190\player-positions.csv
Creating Table player_positions_d190
data/player-positions\VAS\IOL\y1\d121\player-positions.csv
Creating Table player_positions_d121
data/player-positions\VAS\IOL\y1\d122\player-positions.csv
Creating Table player_positions_d122
data/player-positions\VAS\IOL\y1\d123\player-positions.csv
Creating Table player_positions_d123
data/player-positions\VAS\JGO\y1\d198\player-positions.csv
Creating Table player_positions_d198
data/player-positions\VAS\JGO\y1\d199\player-positions.csv
Creating Table player_positions_d199
data/player-positions\VAS\JGO\y1\d200\player-positions.csv
Creating Table player_positions_d200
data/player-positions\VAS\JGO\y1\d201\player-positions.csv
Creating Table player_positions_d201
data/player-positions\VAS\KVN\y1\d142\player-positions.csv
Creating Table player_positions_d142
data/player-positions\VAS\KVN\y1\d143\player-positions.csv
Creating Table player_positions_d143
data/player-positions\VAS\KZR\y1\d159\player-positions.csv
Creating Table player_positions_d159
data/player-positions\VAS\KZR\y1\d160\player-positions.csv
Creating Table player_positions_d160
data/player-positions\VAS\KZR\y1\d161\player-positions.csv
Creating Table player_positions_d161
data/player-positions\VAS\KZR\y1\d162\player-positions.csv
Creating Table player_positions_d162
data/player-positions\VAS\MSN\y1\d104\player-positions.csv
Creating Table player_positions_d104
data/player-positions\VAS\MSN\y1\d105\player-positions.csv
Creating Table player_positions_d105
data/player-positions\VAS\MSN\y1\d106\player-positions.csv
Creating Table player_positions_d106
data/player-positions\VAS\MTW\y1\d174\player-positions.csv
Creating Table player_positions_d174
data/player-positions\VAS\MTW\y1\d175\player-positions.csv
Creating Table player_positions_d175
data/player-positions\VAS\MTW\y1\d176\player-positions.csv
Creating Table player_positions_d176
data/player-positions\VAS\OSW\y1\d086\player-positions.csv
Creating Table player_positions_d086
data/player-positions\VAS\OSW\y1\d087\player-positions.csv
Creating Table player_positions_d087
data/player-positions\VAS\OSW\y1\d088\player-positions.csv
Creating Table player_positions_d088
data/player-positions\VAS\OWV\y1\d171\player-positions.csv
Creating Table player_positions_d171
data/player-positions\VAS\OWV\y1\d172\player-positions.csv
Creating Table player_positions_d172
data/player-positions\VAS\OWV\y1\d173\player-positions.csv
Creating Table player_positions_d173
data/player-positions\VAS\PHD\y1\d077\player-positions.csv
Creating Table player_positions_d077
data/player-positions\VAS\PHD\y1\d077.5\player-positions.csv
Creating Table player_positions_d077_5
data/player-positions\VAS\PHD\y1\d078\player-positions.csv
Creating Table player_positions_d078
data/player-positions\VAS\PHD\y1\d089\player-positions.csv
Creating Table player_positions_d089
data/player-positions\VAS\PHD\y1\d090\player-positions.csv
Creating Table player_positions_d090
data/player-positions\VAS\PHD\y1\d091\player-positions.csv
Creating Table player_positions_d091
data/player-positions\VAS\PHD\y1\d092\player-positions.csv
Creating Table player_positions_d092
data/player-positions\VAS\PHD\y1\d093\player-positions.csv
Creating Table player_positions_d093
data/player-positions\VAS\PHD\y1\d202\player-positions.csv
Creating Table player_positions_d202
data/player-positions\VAS\PHD\y1\d203\player-positions.csv
Creating Table player_positions_d203
data/player-positions\VAS\PHD\y1\d204\player-positions.csv
Creating Table player_positions_d204
data/player-positions\VAS\PHD\y1\d209\player-positions.csv
Creating Table player_positions_d209
data/player-positions\VAS\PHD\y1\d210\player-positions.csv
Creating Table player_positions_d210
data/player-positions\VAS\PHD\y1\d211\player-positions.csv
Creating Table player_positions_d211
data/player-positions\VAS\PHD\y1\d212\player-positions.csv
Creating Table player_positions_d212
data/player-positions\VAS\RRM\y1\d185\player-positions.csv
Creating Table player_positions_d185
data/player-positions\VAS\RRM\y1\d186\player-positions.csv
Creating Table player_positions_d186
data/player-positions\VAS\RRM\y1\d187\player-positions.csv
Creating Table player_positions_d187
data/player-positions\VAS\VNG\y1\d149\player-positions.csv
Creating Table player_positions_d149
data/player-positions\VAS\VNG\y1\d150\player-positions.csv
Creating Table player_positions_d150
data/player-positions\VAS\VNG\y1\d151\player-positions.csv
Creating Table player_positions_d151
data/player-positions\VAS\WDF\y1\d129\player-positions.csv
Creating Table player_positions_d129
data/player-positions\VAS\WDF\y1\d130\player-positions.csv
Creating Table player_positions_d130
data/player-positions\VAS\WDF\y1\d131\player-positions.csv
Creating Table player_positions_d131
data/player-positions\VAS\WTH\y1\d101\player-positions.csv
Creating Table player_positions_d101
data/player-positions\VAS\WTH\y1\d102\player-positions.csv
Creating Table player_positions_d102
data/player-positions\VAS\WTH\y1\d103\player-positions.csv
Creating Table player_positions_d103

In [ ]:
##code used from https://stackoverflow.com/questions/68748559/how-to-merge-multiple-tables-of-large-number-of-columns-with-same-schemas-in-pyt
def merge_events(table_names, c):
    if not len(table_names): return
    
    command ="""CREATE TABLE Events AS\n"""

    for i in range(0, len(table_names)):
        command += "SELECT * FROM {}\n".format(table_names[i])
        if (i != len(table_names) - 1): command += "UNION ALL\n"
    
    c.executescript(command)
merge_events(ball_events_names, cur)

OperationalError: table Events already exists

In [ ]:
def merge_positions(table_names, c):
    if not len(table_names): return
    
    command ="""CREATE TABLE Ball_Pos AS\n"""

    for i in range(0, len(table_names)):
        command += "SELECT * FROM {}\n".format(table_names[i])
        if (i != len(table_names) - 1): command += "UNION ALL\n"
    
    c.executescript(command)
merge_positions(ball_positions_names, cur)

NameError: name 'ball_positions_names' is not defined

In [ ]:
pd.read_sql("SELECT * FROM Ball_Pos;", conn).head(5)

,game_string,play_per_game,timestamp,ball_position_x,ball_position_y,ball_position_z
0,y1_d143_KVN_VAS,1.0,40449.0,-1.924134,52.8543,5.07807
1,y1_d143_KVN_VAS,1.0,40482.0,-1.701486,48.6366,5.01927
2,y1_d143_KVN_VAS,1.0,40515.0,-1.489980,44.4414,4.94433
3,y1_d143_KVN_VAS,1.0,40548.0,-1.289613,40.2687,4.85328
4,y1_d143_KVN_VAS,1.0,40581.0,-1.100388,36.1182,4.74606

In [ ]:
pd.read_sql("SELECT * FROM Events;", conn).head(5)

       game_string  play_per_game  timestamp  player_id  ball_eventcode
0  y1_d143_KVN_VAS            1.0    40449.0          1               1
1  y1_d143_KVN_VAS            1.0    40878.0         10               4
2  y1_d143_KVN_VAS            1.0    47016.0          8               2
3  y1_d143_KVN_VAS            1.0    47115.0          0               5
4  y1_d143_KVN_VAS            2.0    75396.0          1               1

In [ ]:
cur.close()

In [ ]:
db = "barrels.db"
with sql.connect(db, timeout = 1000) as conn:
    cur = conn.cursor()
join_event_with_pos = """
CREATE TABLE Ball_in_play AS
SELECT b.game_string, b.play_per_game, CAST(b.timestamp AS INTEGER) AS timestamp, b.ball_position_x, b.ball_position_y, b.ball_position_z, e.ball_eventcode
FROM Ball_Pos AS b
LEFT JOIN Events AS e
ON b.game_string = e.game_string
AND b.play_per_game = e.play_per_game
AND b.timestamp = e.timestamp
WHERE EXISTS (
SELECT 1
FROM Events AS e2
WHERE e2.game_string = b.game_string
AND e2.play_per_game = b.play_per_game
AND e2.ball_eventcode = 4
ORDER BY b.game_string, b.play_per_game, b.timestamp
)
"""
drop_table = "DROP TABLE IF EXISTS Ball_in_play"
cur.execute(drop_table)
cur.execute(join_event_with_pos)
conn.commit()
pd.read_sql("SELECT * FROM Ball_in_play", conn).head(25)

In [ ]:
del_dup = """
DELETE FROM Ball_in_play
WHERE rowid NOT IN (
    SELECT MIN(rowid)
    FROM Ball_in_play
    GROUP BY game_string, play_per_game, timestamp
)
"""
cur.execute(del_dup)
conn.commit()
pd.read_sql("SELECT * FROM Ball_in_play", conn).head(25)

,game_string,play_per_game,timestamp,ball_position_x,ball_position_y,ball_position_z,ball_eventcode
0,y1_d143_KVN_VAS,1.0,40449,-1.924134,52.854300,5.07807,1.0
1,y1_d143_KVN_VAS,1.0,40482,-1.701486,48.636600,5.01927,NaN
2,y1_d143_KVN_VAS,1.0,40515,-1.489980,44.441400,4.94433,NaN
3,y1_d143_KVN_VAS,1.0,40548,-1.289613,40.268700,4.85328,NaN
4,y1_d143_KVN_VAS,1.0,40581,-1.100388,36.118200,4.74606,NaN
5,y1_d143_KVN_VAS,1.0,40614,-0.922305,31.990200,4.62276,NaN
6,y1_d143_KVN_VAS,1.0,40647,-0.755361,27.884400,4.48332,NaN
7,y1_d143_KVN_VAS,1.0,40680,-0.599562,23.801040,4.32774,NaN
8,y1_d143_KVN_VAS,1.0,40713,-0.454902,19.740000,4.15602,NaN
9,y1_d143_KVN_VAS,1.0,40746,-0.321384,15.701340,3.96822,NaN
10,y1_d143_KVN_VAS,1.0,40779,-0.199007,11.685030,3.76425,NaN
11,y1_d143_KVN_VAS,1.0,40812,-0.087771,7.691070,3.54417,NaN
12,y1_d143_KVN_VAS,1.0,40845,0.012323,3.719490,3.30795,NaN
13,y1_d143_KVN_VAS,1.0,40878,0.101276,-0.229754,3.05562,4.0
14,y1_d143_KVN_VAS,1.0,40911,-1.323243,7.540470,6.78753,NaN
15,y1_d143_KVN_VAS,1.0,40944,-2.250612,10.884180,10.09074,NaN
16,y1_d143_KVN_VAS,1.0,40977,-3.172920,14.210040,13.35798,NaN
17,y1_d143_KVN_VAS,1.0,41010,-4.090200,17.518020,16.58925,NaN
18,y1_d143_KVN_VAS,1.0,41043,-5.002410,20.808180,19.78458,NaN
19,y1_d143_KVN_VAS,1.0,41076,-5.909580,24.080460,22.94394,NaN
20,y1_d143_KVN_VAS,1.0,41109,-6.811710,27.334920,26.06733,NaN
21,y1_d143_KVN_VAS,1.0,41142,-7.708770,30.571500,29.15478,NaN
22,y1_d143_KVN_VAS,1.0,41175,-8.600790,33.790200,32.20620,NaN
23,y1_d143_KVN_VAS,1.0,41208,-9.487770,36.991200,35.22180,NaN
24,y1_d143_KVN_VAS,1.0,41241,-10.369680,40.174200,38.20140,NaN

In [ ]:
pd.read_sql("SELECT * FROM Ball_in_play ORDER BY game_string, play_per_game, timestamp", conn).head(10)

,game_string,play_per_game,timestamp,ball_position_x,ball_position_y,ball_position_z,ball_eventcode
0,y1_d061_VKA_PHD,2.0,75964,-2.395110,58.046400,5.937720,1.0
1,y1_d061_VKA_PHD,2.0,76014,-2.042184,51.149100,5.660850,NaN
2,y1_d061_VKA_PHD,2.0,76064,-1.709583,44.328000,5.333700,NaN
3,y1_d061_VKA_PHD,2.0,76114,-1.397307,37.582800,4.956210,NaN
4,y1_d061_VKA_PHD,2.0,76164,-1.105356,30.913500,4.528410,NaN
5,y1_d061_VKA_PHD,2.0,76214,-0.833733,24.320130,4.050330,NaN
6,y1_d061_VKA_PHD,2.0,76264,-0.582432,17.802810,3.521910,NaN
7,y1_d061_VKA_PHD,2.0,76314,-0.351456,11.361540,2.943198,NaN
8,y1_d061_VKA_PHD,2.0,76364,-0.140807,4.996260,2.314173,NaN
9,y1_d061_VKA_PHD,2.0,76414,0.049517,-1.293039,1.634838,4.0

In [ ]:
drop_table = "DROP TABLE IF EXISTS barrel_calc"
cur.execute(drop_table)
barrel_calc = """
CREATE TABLE barrel_calc AS
WITH contact AS (
SELECT b2.game_string, b2.play_per_game, b2.timestamp AS start
FROM Ball_in_play as b2
WHERE b2.ball_eventcode = 4
)
SELECT b.game_string, b.play_per_game, b.timestamp, b.ball_position_x, b.ball_position_y, b.ball_position_z
FROM Ball_in_play AS b
    JOIN contact AS c
    ON b.game_string = c.game_string
    AND b.play_per_game = c.play_per_game
WHERE b.timestamp >= start AND b.timestamp <= start + 250
ORDER BY b.game_string, b.play_per_game, b.timestamp
"""
cur.execute(barrel_calc)
conn.commit()
pd.read_sql("SELECT * FROM barrel_calc", conn).head(25)

OperationalError: no such table: Ball_in_play

In [ ]:
drop_table = "DROP TABLE IF EXISTS ev_la"
cur.execute(drop_table)
drop_table = "DROP TABLE IF EXISTS delta_phys"
cur.execute(drop_table)
ev = """
CREATE TABLE ev_la AS
WITH delta_ts AS (
SELECT game_string, 
    play_per_game, 
    MIN(timestamp) AS start, 
    MAX(timestamp) AS end_time, 
    (MAX(timestamp) - MIN(timestamp)) / 1000.0 AS delta_t
FROM barrel_calc
GROUP BY game_string, play_per_game
),
delta_phys AS (
SELECT t.game_string,
    t.play_per_game,
    start_row.ball_position_x * 12 as start_x,
    start_row.ball_position_y * 12 as start_y, 
    start_row.ball_position_z * 12 as start_z,
    end_row.ball_position_x * 12 as end_x,
    end_row.ball_position_y * 12 as end_y, 
    end_row.ball_position_z * 12 as end_z
FROM delta_ts as t
JOIN barrel_calc start_row
    ON start_row.game_string = t.game_string
    AND start_row.play_per_game = t.play_per_game
    AND start_row.timestamp = t.start
JOIN barrel_calc end_row
    ON end_row.game_string = t.game_string
    AND end_row.play_per_game = t.play_per_game
    AND end_row.timestamp = t.end_time
)
SELECT
    t2.game_string,
    t2.play_per_game,
    sqrt(pow((p2.end_x - p2.start_x) / t2.delta_t ,2) + pow((p2.end_y - p2.start_y) / t2.delta_t ,2) + pow((p2.end_z - p2.start_z) / t2.delta_t ,2)) / 17.6 AS exit_velocity,
    asin((p2.end_z - p2.start_z) / sqrt(pow((p2.end_x - p2.start_x), 2) + pow((p2.end_y - p2.start_y), 2) + pow((p2.end_z - p2.start_z) ,2))) * 180 / pi() AS launch_angle
FROM delta_ts AS t2
JOIN delta_phys AS p2
ON t2.game_string = p2.game_string
AND t2.play_per_game = p2.play_per_game
ORDER BY t2.game_string, t2.play_per_game
"""
cur.execute(ev)
conn.commit()
pd.read_sql("SELECT * FROM ev_la", conn).head(25)

OperationalError: no such table: barrel_calc

In [ ]:
del_null = """
DELETE FROM ev_la
WHERE exit_velocity IS NULL AND launch_angle IS NULL
"""
cur.execute(del_null)
conn.commit()
pd.read_sql("SELECT * FROM ev_la", conn).head(25)

OperationalError: no such table: ev_la

In [ ]:
cur.execute("ALTER TABLE ev_la ADD COLUMN barrel")
barrel_classifier = """
UPDATE ev_la SET barrel = 1 
WHERE exit_velocity >= 98.0 
AND launch_angle >= 26 - (exit_velocity - 98) * 1.5 
AND launch_angle <= 30 + (exit_velocity - 98) * 1.5;
"""
cur.execute(barrel_classifier)
conn.commit()
barrel_classifier = """
UPDATE ev_la SET barrel = 0 
WHERE exit_velocity <= 98.0 
OR launch_angle <= 26 - (exit_velocity - 98) * 1.5 
OR launch_angle >= 30 + (exit_velocity - 98) * 1.5;
"""
cur.execute(barrel_classifier)
conn.commit()
pd.read_sql("SELECT * FROM ev_la", conn).head(50)

OperationalError: no such table: ev_la

In [ ]:
pd.read_sql("SELECT COUNT(*) FROM ev_la WHERE barrel = 1", conn).head(50)

DatabaseError: Execution failed on sql 'SELECT COUNT(*) FROM ev_la WHERE barrel = 1': no such table: ev_la

In [ ]:
pd.read_sql("SELECT COUNT(*) FROM ev_la", conn).head(50)

DatabaseError: Execution failed on sql 'SELECT COUNT(*) FROM ev_la': no such table: ev_la

In [ ]:
656/7485

0.08764195056780227

In [ ]:
import csv

with sql.connect("barrels.db") as connection:
    csvWriter = csv.writer(open("barrels.csv", "w", newline=""))
    c = connection.cursor()
    c.execute("SELECT * FROM ev_la")
    csvWriter.writerow(['game_string','play_per_game','exit_velocity','launch_angle','barrel'])
    rows = c.fetchall()
    csvWriter.writerows(rows)

In [ ]:
conn.close()

In [ ]:
for file in glob.glob("data/*.csv"):
    df = pd.read_csv(file)
    print("Creating Table", file[5:-4].replace("-",""))
    df.to_sql(file[5:-4].replace("-",""), conn, if_exists="replace", index=False)

Creating Table gameinfo

ProgrammingError: Cannot operate on a closed database.

In [ ]:
for file in glob.glob("./*.csv"):
    df = pd.read_csv(file)
    print("Creating Table", file[2:-4].replace("-",""))
    df.to_sql(file[2:-4].replace("-",""), conn, if_exists="replace", index=False)

Creating Table barrels

ProgrammingError: Cannot operate on a closed database.

In [ ]:
pd.read_sql("SELECT * FROM ev_la", conn).head(1)

ProgrammingError: Cannot operate on a closed database.

In [ ]:
pd.read_sql("SELECT * FROM first_pitches ORDER BY game_string, play_per_game", conn).head(1)

,game_string,play_per_game,pitch_release_time,pitch_end_time,result_in_play,first_pitch,pitcher,batter
0,NaN,NaN,NaN,NaN,1,1,NaN,NaN

In [ ]:
db = "barrels.db"
with sql.connect(db, timeout = 1000) as conn:
    cur = conn.cursor()
join_event_with_pos = """
CREATE TABLE First_pitch_barrel
SELECT b.game_string, b.play_per_game, CAST(b.timestamp AS INTEGER) AS timestamp, b.ball_position_x, b.ball_position_y, b.ball_position_z, e.ball_eventcode
FROM Ball_Pos AS b
LEFT JOIN Events AS e
ON b.game_string = e.game_string
AND b.play_per_game = e.play_per_game
AND b.timestamp = e.timestamp
WHERE EXISTS (
SELECT 1
FROM Events AS e2
WHERE e2.game_string = b.game_string
AND e2.play_per_game = b.play_per_game
AND e2.ball_eventcode = 4
ORDER BY b.game_string, b.play_per_game, b.timestamp
)
"""
drop_table = "DROP TABLE IF EXISTS Ball_in_play"
cur.execute(drop_table)
cur.execute(join_event_with_pos)
conn.commit()
pd.read_sql("SELECT * FROM Ball_in_play", conn).head(25)

OperationalError: near "SELECT": syntax error

In [ ]:
db = "barrels.db"
with sql.connect(db, timeout = 1000) as conn:
    cur = conn.cursor()
join_fp_bar = """
CREATE TABLE First_pitch_barrel
AS
SELECT f.game_string, f.play_per_game, f.pitch_release_time, f.pitch_end_time, f.result_in_play, f.first_pitch, f.pitcher, f.batter, b.barrel, b.exit_velocity, b.launch_angle
FROM first_pitches AS f
LEFT JOIN ev_la AS b
ON f.game_string = b.game_string 
AND f.play_per_game = b.play_per_game
ORDER BY f.game_string, f.play_per_game
"""
drop_table = "DROP TABLE IF EXISTS First_pitch_barrel"
cur.execute(drop_table)
cur.execute(join_fp_bar)
conn.commit()
pd.read_sql("SELECT * FROM First_pitch_barrel", conn).head(25)

,game_string,play_per_game,pitch_release_time,pitch_end_time,result_in_play,first_pitch,pitcher,batter,barrel,exit_velocity,launch_angle
0,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN
2,y1_d061_VKA_PHD,1.0,63614.0,64064.0,0,1,PHD-4341,VKA-5565,NaN,NaN,NaN
3,y1_d061_VKA_PHD,3.0,109614.0,110014.0,1,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
4,y1_d061_VKA_PHD,3.0,109614.0,110064.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
5,y1_d061_VKA_PHD,3.0,109614.0,111364.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
6,y1_d061_VKA_PHD,3.0,109614.0,112164.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
7,y1_d061_VKA_PHD,3.0,109614.0,114164.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
8,y1_d061_VKA_PHD,4.0,145414.0,145914.0,0,1,PHD-4341,VKA-7206,NaN,NaN,NaN
9,y1_d061_VKA_PHD,9.0,370464.0,370964.0,0,1,VKA-1417,PHD-8619,NaN,NaN,NaN
10,y1_d061_VKA_PHD,12.0,441264.0,441764.0,0,1,VKA-1417,PHD-7743,NaN,NaN,NaN
11,y1_d061_VKA_PHD,15.0,523214.0,523764.0,0,1,VKA-1417,PHD-6069,NaN,NaN,NaN
12,y1_d061_VKA_PHD,19.0,640814.0,641364.0,0,1,VKA-1417,PHD-7166,NaN,NaN,NaN
13,y1_d061_VKA_PHD,23.0,877814.0,878214.0,1,1,PHD-4341,VKA-2765,NaN,NaN,NaN
14,y1_d061_VKA_PHD,26.0,945564.0,946114.0,0,1,PHD-4341,VKA-8440,NaN,NaN,NaN
15,y1_d061_VKA_PHD,29.0,1007714.0,1008214.0,0,1,PHD-4341,VKA-0515,NaN,NaN,NaN
16,y1_d061_VKA_PHD,35.0,1125314.0,1125764.0,1,1,PHD-4341,VKA-0045,1.0,120.242186,14.683704
17,y1_d061_VKA_PHD,35.0,1125314.0,1128314.0,0,1,PHD-4341,VKA-0045,1.0,120.242186,14.683704
18,y1_d061_VKA_PHD,36.0,1253414.0,1253914.0,0,1,VKA-1417,PHD-5504,NaN,NaN,NaN
19,y1_d061_VKA_PHD,38.0,1296314.0,1296764.0,0,1,VKA-1417,PHD-9663,NaN,NaN,NaN
20,y1_d061_VKA_PHD,43.0,1377914.0,1378364.0,0,1,VKA-1417,PHD-5994,NaN,NaN,NaN
21,y1_d061_VKA_PHD,48.0,1481764.0,1482314.0,0,1,VKA-1417,PHD-4573,NaN,NaN,NaN
22,y1_d061_VKA_PHD,50.0,1645814.0,1646314.0,0,1,PHD-4341,VKA-3145,NaN,NaN,NaN
23,y1_d061_VKA_PHD,54.0,1721164.0,1721664.0,0,1,PHD-4341,VKA-6464,NaN,NaN,NaN
24,y1_d061_VKA_PHD,59.0,1829464.0,1829914.0,0,1,PHD-4341,VKA-5565,NaN,NaN,NaN

In [ ]:
del_null = """
DELETE FROM First_pitch_barrel
WHERE pitcher IS NULL AND batter IS NULL
"""
cur.execute(del_null)
conn.commit()
pd.read_sql("SELECT * FROM First_pitch_barrel", conn).head(25)

,game_string,play_per_game,pitch_release_time,pitch_end_time,result_in_play,first_pitch,pitcher,batter,barrel,exit_velocity,launch_angle
0,y1_d061_VKA_PHD,1.0,63614.0,64064.0,0,1,PHD-4341,VKA-5565,NaN,NaN,NaN
1,y1_d061_VKA_PHD,3.0,109614.0,110014.0,1,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
2,y1_d061_VKA_PHD,3.0,109614.0,110064.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
3,y1_d061_VKA_PHD,3.0,109614.0,111364.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
4,y1_d061_VKA_PHD,3.0,109614.0,112164.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
5,y1_d061_VKA_PHD,3.0,109614.0,114164.0,0,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
6,y1_d061_VKA_PHD,4.0,145414.0,145914.0,0,1,PHD-4341,VKA-7206,NaN,NaN,NaN
7,y1_d061_VKA_PHD,9.0,370464.0,370964.0,0,1,VKA-1417,PHD-8619,NaN,NaN,NaN
8,y1_d061_VKA_PHD,12.0,441264.0,441764.0,0,1,VKA-1417,PHD-7743,NaN,NaN,NaN
9,y1_d061_VKA_PHD,15.0,523214.0,523764.0,0,1,VKA-1417,PHD-6069,NaN,NaN,NaN
10,y1_d061_VKA_PHD,19.0,640814.0,641364.0,0,1,VKA-1417,PHD-7166,NaN,NaN,NaN
11,y1_d061_VKA_PHD,23.0,877814.0,878214.0,1,1,PHD-4341,VKA-2765,NaN,NaN,NaN
12,y1_d061_VKA_PHD,26.0,945564.0,946114.0,0,1,PHD-4341,VKA-8440,NaN,NaN,NaN
13,y1_d061_VKA_PHD,29.0,1007714.0,1008214.0,0,1,PHD-4341,VKA-0515,NaN,NaN,NaN
14,y1_d061_VKA_PHD,35.0,1125314.0,1125764.0,1,1,PHD-4341,VKA-0045,1.0,120.242186,14.683704
15,y1_d061_VKA_PHD,35.0,1125314.0,1128314.0,0,1,PHD-4341,VKA-0045,1.0,120.242186,14.683704
16,y1_d061_VKA_PHD,36.0,1253414.0,1253914.0,0,1,VKA-1417,PHD-5504,NaN,NaN,NaN
17,y1_d061_VKA_PHD,38.0,1296314.0,1296764.0,0,1,VKA-1417,PHD-9663,NaN,NaN,NaN
18,y1_d061_VKA_PHD,43.0,1377914.0,1378364.0,0,1,VKA-1417,PHD-5994,NaN,NaN,NaN
19,y1_d061_VKA_PHD,48.0,1481764.0,1482314.0,0,1,VKA-1417,PHD-4573,NaN,NaN,NaN
20,y1_d061_VKA_PHD,50.0,1645814.0,1646314.0,0,1,PHD-4341,VKA-3145,NaN,NaN,NaN
21,y1_d061_VKA_PHD,54.0,1721164.0,1721664.0,0,1,PHD-4341,VKA-6464,NaN,NaN,NaN
22,y1_d061_VKA_PHD,59.0,1829464.0,1829914.0,0,1,PHD-4341,VKA-5565,NaN,NaN,NaN
23,y1_d061_VKA_PHD,63.0,2001714.0,2002114.0,1,1,VKA-1417,PHD-0812,NaN,NaN,NaN
24,y1_d061_VKA_PHD,65.0,2056664.0,2057164.0,0,1,VKA-1417,PHD-8619,NaN,NaN,NaN

In [ ]:
del_dup = """
DELETE FROM First_pitch_barrel
WHERE rowid NOT IN (
    SELECT MIN(rowid)
    FROM First_pitch_barrel
    GROUP BY game_string, play_per_game, pitch_release_time
)
"""
cur.execute(del_dup)
conn.commit()
pd.read_sql("SELECT * FROM First_pitch_barrel", conn).head(25)

,game_string,play_per_game,pitch_release_time,pitch_end_time,result_in_play,first_pitch,pitcher,batter,barrel,exit_velocity,launch_angle
0,y1_d061_VKA_PHD,1.0,63614.0,64064.0,0,1,PHD-4341,VKA-5565,NaN,NaN,NaN
1,y1_d061_VKA_PHD,3.0,109614.0,110014.0,1,1,PHD-4341,VKA-7844,0.0,58.839984,9.500162
2,y1_d061_VKA_PHD,4.0,145414.0,145914.0,0,1,PHD-4341,VKA-7206,NaN,NaN,NaN
3,y1_d061_VKA_PHD,9.0,370464.0,370964.0,0,1,VKA-1417,PHD-8619,NaN,NaN,NaN
4,y1_d061_VKA_PHD,12.0,441264.0,441764.0,0,1,VKA-1417,PHD-7743,NaN,NaN,NaN
5,y1_d061_VKA_PHD,15.0,523214.0,523764.0,0,1,VKA-1417,PHD-6069,NaN,NaN,NaN
6,y1_d061_VKA_PHD,19.0,640814.0,641364.0,0,1,VKA-1417,PHD-7166,NaN,NaN,NaN
7,y1_d061_VKA_PHD,23.0,877814.0,878214.0,1,1,PHD-4341,VKA-2765,NaN,NaN,NaN
8,y1_d061_VKA_PHD,26.0,945564.0,946114.0,0,1,PHD-4341,VKA-8440,NaN,NaN,NaN
9,y1_d061_VKA_PHD,29.0,1007714.0,1008214.0,0,1,PHD-4341,VKA-0515,NaN,NaN,NaN
10,y1_d061_VKA_PHD,35.0,1125314.0,1125764.0,1,1,PHD-4341,VKA-0045,1.0,120.242186,14.683704
11,y1_d061_VKA_PHD,36.0,1253414.0,1253914.0,0,1,VKA-1417,PHD-5504,NaN,NaN,NaN
12,y1_d061_VKA_PHD,38.0,1296314.0,1296764.0,0,1,VKA-1417,PHD-9663,NaN,NaN,NaN
13,y1_d061_VKA_PHD,43.0,1377914.0,1378364.0,0,1,VKA-1417,PHD-5994,NaN,NaN,NaN
14,y1_d061_VKA_PHD,48.0,1481764.0,1482314.0,0,1,VKA-1417,PHD-4573,NaN,NaN,NaN
15,y1_d061_VKA_PHD,50.0,1645814.0,1646314.0,0,1,PHD-4341,VKA-3145,NaN,NaN,NaN
16,y1_d061_VKA_PHD,54.0,1721164.0,1721664.0,0,1,PHD-4341,VKA-6464,NaN,NaN,NaN
17,y1_d061_VKA_PHD,59.0,1829464.0,1829914.0,0,1,PHD-4341,VKA-5565,NaN,NaN,NaN
18,y1_d061_VKA_PHD,63.0,2001714.0,2002114.0,1,1,VKA-1417,PHD-0812,NaN,NaN,NaN
19,y1_d061_VKA_PHD,65.0,2056664.0,2057164.0,0,1,VKA-1417,PHD-8619,NaN,NaN,NaN
20,y1_d061_VKA_PHD,70.0,2185864.0,2186314.0,0,1,VKA-1417,PHD-7743,NaN,NaN,NaN
21,y1_d061_VKA_PHD,72.0,2249714.0,2250214.0,0,1,VKA-1417,PHD-6069,NaN,NaN,NaN
22,y1_d061_VKA_PHD,76.0,2356014.0,2356514.0,0,1,VKA-1417,PHD-7166,NaN,NaN,NaN
23,y1_d061_VKA_PHD,78.0,2520014.0,2520564.0,0,1,PHD-4341,VKA-7844,NaN,NaN,NaN
24,y1_d061_VKA_PHD,83.0,2614314.0,2614764.0,0,1,PHD-4341,VKA-7206,NaN,NaN,NaN

In [ ]:
pd.read_sql("SELECT COUNT(*) FROM First_pitch_barrel WHERE barrel = 1.0", conn).head(50)

   COUNT(*)
0       171

In [ ]:
drop_table = "DROP TABLE IF EXISTS leaderboard"
cur.execute(drop_table)
leaderboard = """
CREATE TABLE leaderboard
AS
SELECT batter, SUM(barrel) AS barrels
FROM First_pitch_barrel
GROUP BY batter
"""
cur.execute(leaderboard)
conn.commit()

In [ ]:
del_0 = """
DELETE FROM leaderboard
WHERE barrels < 0.5 OR barrels is NULL
"""
cur.execute(del_0)
conn.commit()

In [ ]:
pd.read_sql("SELECT * FROM leaderboard ORDER BY barrels DESC", conn).head(25)

      batter  barrels
0   PHD-1580        7
1   PHD-5504        6
2   PHD-7166        6
3   PHD-8619        5
4   VAS-4154        5
5   VAS-4675        5
6   PHD-7743        4
7   PHD-0812        3
8   PHD-1790        3
9   PHD-2671        3
10  PHD-3597        3
11  PHD-5994        3
12  PHD-6069        3
13  PHD-9663        3
14  VAS-1773        3
15  VAS-3928        3
16  VAS-5976        3
17  VAS-7569        3
18  ANI-2218        2
19  ARN-3382        2
20  ARN-6201        2
21  ARN-8020        2
22  ATL-7836        2
23  BXH-6383        2
24  MKS-5459        2